# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hset.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hset.proto',
  package='com.htsc.xquant.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\nhset.proto\x12\x18\x63om.htsc.xquant.protobuf\"U\n\x0bHsetRequest\x12\x11\n\tplateType\x18\x01 \x01(\x05\x12\x0f\n\x07plateId\x18\x02 \x01(\t\x12\x11\n\tstartTime\x18\x03 \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x04 \x01(\t\",\n\tStockInfo\x12\x10\n\x08\x64\x61teTime\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"k\n\x0cHsetResponse\x12\x12\n\nresultCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x36\n\tstockInfo\x18\x03 \x03(\x0b\x32#.com.htsc.xquant.protobuf.StockInfo2h\n\x0bHsetService\x12Y\n\x04hset\x12%.com.htsc.xquant.protobuf.HsetRequest\x1a&.com.htsc.xquant.protobuf.HsetResponse\"\x00\x30\x01\x42\x39\n*com.htsc.xquant.factor.datacenter.protobufB\tHsetProtoP\x01\x62\x06proto3')
)




_HSETREQUEST = _descriptor.Descriptor(
  name='HsetRequest',
  full_name='com.htsc.xquant.protobuf.HsetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plateType', full_name='com.htsc.xquant.protobuf.HsetRequest.plateType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plateId', full_name='com.htsc.xquant.protobuf.HsetRequest.plateId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='com.htsc.xquant.protobuf.HsetRequest.startTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='com.htsc.xquant.protobuf.HsetRequest.endTime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=125,
)


_STOCKINFO = _descriptor.Descriptor(
  name='StockInfo',
  full_name='com.htsc.xquant.protobuf.StockInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dateTime', full_name='com.htsc.xquant.protobuf.StockInfo.dateTime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.htsc.xquant.protobuf.StockInfo.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=171,
)


_HSETRESPONSE = _descriptor.Descriptor(
  name='HsetResponse',
  full_name='com.htsc.xquant.protobuf.HsetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='com.htsc.xquant.protobuf.HsetResponse.resultCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.htsc.xquant.protobuf.HsetResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stockInfo', full_name='com.htsc.xquant.protobuf.HsetResponse.stockInfo', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=280,
)

_HSETRESPONSE.fields_by_name['stockInfo'].message_type = _STOCKINFO
DESCRIPTOR.message_types_by_name['HsetRequest'] = _HSETREQUEST
DESCRIPTOR.message_types_by_name['StockInfo'] = _STOCKINFO
DESCRIPTOR.message_types_by_name['HsetResponse'] = _HSETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HsetRequest = _reflection.GeneratedProtocolMessageType('HsetRequest', (_message.Message,), dict(
  DESCRIPTOR = _HSETREQUEST,
  __module__ = 'hset_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.HsetRequest)
  ))
_sym_db.RegisterMessage(HsetRequest)

StockInfo = _reflection.GeneratedProtocolMessageType('StockInfo', (_message.Message,), dict(
  DESCRIPTOR = _STOCKINFO,
  __module__ = 'hset_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.StockInfo)
  ))
_sym_db.RegisterMessage(StockInfo)

HsetResponse = _reflection.GeneratedProtocolMessageType('HsetResponse', (_message.Message,), dict(
  DESCRIPTOR = _HSETRESPONSE,
  __module__ = 'hset_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.HsetResponse)
  ))
_sym_db.RegisterMessage(HsetResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.htsc.xquant.factor.datacenter.protobufB\tHsetProtoP\001'))

_HSETSERVICE = _descriptor.ServiceDescriptor(
  name='HsetService',
  full_name='com.htsc.xquant.protobuf.HsetService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=282,
  serialized_end=386,
  methods=[
  _descriptor.MethodDescriptor(
    name='hset',
    full_name='com.htsc.xquant.protobuf.HsetService.hset',
    index=0,
    containing_service=None,
    input_type=_HSETREQUEST,
    output_type=_HSETRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HSETSERVICE)

DESCRIPTOR.services_by_name['HsetService'] = _HSETSERVICE

# @@protoc_insertion_point(module_scope)