# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from .indexTrading_pb2 import *


class IndexTradingServiceStub(object):
  """指数成分股查询rpc
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getIndexTrading = channel.unary_unary(
        '/com.htsc.xquant.protobuf.IndexTradingService/getIndexTrading',
        request_serializer=GetIndexTradingRequest.SerializeToString,
        response_deserializer=GetIndexTradingResponse.FromString,
        )


class IndexTradingServiceServicer(object):
  """指数成分股查询rpc
  """

  def getIndexTrading(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IndexTradingServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getIndexTrading': grpc.unary_unary_rpc_method_handler(
          servicer.getIndexTrading,
          request_deserializer=GetIndexTradingRequest.FromString,
          response_serializer=GetIndexTradingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.htsc.xquant.protobuf.IndexTradingService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))