# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jurisdictionControl.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jurisdictionControl.proto',
  package='com.htsc.xquant.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x19jurisdictionControl.proto\x12\x18\x63om.htsc.xquant.protobuf\"|\n\x13JurisdictionRequest\x12\x13\n\x0buserAccount\x18\x01 \x01(\t\x12\x14\n\x0c\x66\x61\x63torIdList\x18\x02 \x01(\t\x12\x1d\n\x15jurisdictionDateStart\x18\x03 \x01(\t\x12\x1b\n\x13jurisdictionDateEnd\x18\x04 \x01(\t\"7\n\x10JurisdictionData\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"W\n\x14JurisdictionResponse\x12?\n\x0bmessageList\x18\x01 \x03(\x0b\x32*.com.htsc.xquant.protobuf.JurisdictionData2\x91\x01\n\x13JurisdictionService\x12z\n\x15getFactorJurisdiction\x12-.com.htsc.xquant.protobuf.JurisdictionRequest\x1a..com.htsc.xquant.protobuf.JurisdictionResponse\"\x00\x30\x01\x42H\n*com.htsc.xquant.factor.datacenter.protobufB\x18JurisdictionServiceProtoP\x01\x62\x06proto3')
)




_JURISDICTIONREQUEST = _descriptor.Descriptor(
  name='JurisdictionRequest',
  full_name='com.htsc.xquant.protobuf.JurisdictionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userAccount', full_name='com.htsc.xquant.protobuf.JurisdictionRequest.userAccount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='factorIdList', full_name='com.htsc.xquant.protobuf.JurisdictionRequest.factorIdList', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jurisdictionDateStart', full_name='com.htsc.xquant.protobuf.JurisdictionRequest.jurisdictionDateStart', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jurisdictionDateEnd', full_name='com.htsc.xquant.protobuf.JurisdictionRequest.jurisdictionDateEnd', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=179,
)


_JURISDICTIONDATA = _descriptor.Descriptor(
  name='JurisdictionData',
  full_name='com.htsc.xquant.protobuf.JurisdictionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='com.htsc.xquant.protobuf.JurisdictionData.statusCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.htsc.xquant.protobuf.JurisdictionData.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=236,
)


_JURISDICTIONRESPONSE = _descriptor.Descriptor(
  name='JurisdictionResponse',
  full_name='com.htsc.xquant.protobuf.JurisdictionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageList', full_name='com.htsc.xquant.protobuf.JurisdictionResponse.messageList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=325,
)

_JURISDICTIONRESPONSE.fields_by_name['messageList'].message_type = _JURISDICTIONDATA
DESCRIPTOR.message_types_by_name['JurisdictionRequest'] = _JURISDICTIONREQUEST
DESCRIPTOR.message_types_by_name['JurisdictionData'] = _JURISDICTIONDATA
DESCRIPTOR.message_types_by_name['JurisdictionResponse'] = _JURISDICTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JurisdictionRequest = _reflection.GeneratedProtocolMessageType('JurisdictionRequest', (_message.Message,), dict(
  DESCRIPTOR = _JURISDICTIONREQUEST,
  __module__ = 'jurisdictionControl_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.JurisdictionRequest)
  ))
_sym_db.RegisterMessage(JurisdictionRequest)

JurisdictionData = _reflection.GeneratedProtocolMessageType('JurisdictionData', (_message.Message,), dict(
  DESCRIPTOR = _JURISDICTIONDATA,
  __module__ = 'jurisdictionControl_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.JurisdictionData)
  ))
_sym_db.RegisterMessage(JurisdictionData)

JurisdictionResponse = _reflection.GeneratedProtocolMessageType('JurisdictionResponse', (_message.Message,), dict(
  DESCRIPTOR = _JURISDICTIONRESPONSE,
  __module__ = 'jurisdictionControl_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.JurisdictionResponse)
  ))
_sym_db.RegisterMessage(JurisdictionResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.htsc.xquant.factor.datacenter.protobufB\030JurisdictionServiceProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class JurisdictionServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.getFactorJurisdiction = channel.unary_stream(
          '/com.htsc.xquant.protobuf.JurisdictionService/getFactorJurisdiction',
          request_serializer=JurisdictionRequest.SerializeToString,
          response_deserializer=JurisdictionResponse.FromString,
          )


  class JurisdictionServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def getFactorJurisdiction(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_JurisdictionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'getFactorJurisdiction': grpc.unary_stream_rpc_method_handler(
            servicer.getFactorJurisdiction,
            request_deserializer=JurisdictionRequest.FromString,
            response_serializer=JurisdictionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'com.htsc.xquant.protobuf.JurisdictionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaJurisdictionServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def getFactorJurisdiction(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaJurisdictionServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def getFactorJurisdiction(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()


  def beta_create_JurisdictionService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('com.htsc.xquant.protobuf.JurisdictionService', 'getFactorJurisdiction'): JurisdictionRequest.FromString,
    }
    response_serializers = {
      ('com.htsc.xquant.protobuf.JurisdictionService', 'getFactorJurisdiction'): JurisdictionResponse.SerializeToString,
    }
    method_implementations = {
      ('com.htsc.xquant.protobuf.JurisdictionService', 'getFactorJurisdiction'): face_utilities.unary_stream_inline(servicer.getFactorJurisdiction),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_JurisdictionService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('com.htsc.xquant.protobuf.JurisdictionService', 'getFactorJurisdiction'): JurisdictionRequest.SerializeToString,
    }
    response_deserializers = {
      ('com.htsc.xquant.protobuf.JurisdictionService', 'getFactorJurisdiction'): JurisdictionResponse.FromString,
    }
    cardinalities = {
      'getFactorJurisdiction': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'com.htsc.xquant.protobuf.JurisdictionService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)