# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EMDValidType.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EMDValidType.proto',
  package='com.htsc.mdc.model',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x45MDValidType.proto\x12\x12\x63om.htsc.mdc.model*_\n\x0c\x45MDValidType\x12\t\n\x05Valid\x10\x00\x12\x0b\n\x07Invalid\x10\x01\x12\x1f\n\x1bInvalidDueToTotalValueTrade\x10\n\x12\x16\n\x12InvalidDueToMDTime\x10\x0b\x42-\n\x12\x63om.htsc.mdc.modelB\x12\x45MDValidTypeProtosH\x01\xa0\x01\x01\x62\x06proto3')
)

_EMDVALIDTYPE = _descriptor.EnumDescriptor(
  name='EMDValidType',
  full_name='com.htsc.mdc.model.EMDValidType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Valid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Invalid', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidDueToTotalValueTrade', index=2, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='InvalidDueToMDTime', index=3, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=42,
  serialized_end=137,
)
_sym_db.RegisterEnumDescriptor(_EMDVALIDTYPE)

EMDValidType = enum_type_wrapper.EnumTypeWrapper(_EMDVALIDTYPE)
Valid = 0
Invalid = 1
InvalidDueToTotalValueTrade = 10
InvalidDueToMDTime = 11


DESCRIPTOR.enum_types_by_name['EMDValidType'] = _EMDVALIDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022com.htsc.mdc.modelB\022EMDValidTypeProtosH\001\240\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
