# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ESecurityIDSource.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ESecurityIDSource.proto',
  package='com.htsc.mdc.model',
  syntax='proto3',
  serialized_pb=_b('\n\x17\x45SecurityIDSource.proto\x12\x12\x63om.htsc.mdc.model*\x91\x01\n\x11\x45SecurityIDSource\x12\x1b\n\x17\x44\x65\x66\x61ultSecurityIDSource\x10\x00\x12\x08\n\x04XSHG\x10\x65\x12\x08\n\x04XSHE\x10\x66\x12\t\n\x04XHKG\x10\xcb\x01\x12\t\n\x04\x43\x43\x46X\x10\xad\x02\x12\t\n\x04XSGE\x10\xae\x02\x12\t\n\x04SGEX\x10\x91\x03\x12\t\n\x04XCFE\x10\xf5\x03\x12\t\n\x04XDCE\x10\xd9\x04\x12\t\n\x04XZCE\x10\xda\x04\x42\x32\n\x12\x63om.htsc.mdc.modelB\x17\x45SecurityIDSourceProtosH\x01\xa0\x01\x01\x62\x06proto3')
)

_ESECURITYIDSOURCE = _descriptor.EnumDescriptor(
  name='ESecurityIDSource',
  full_name='com.htsc.mdc.model.ESecurityIDSource',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DefaultSecurityIDSource', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XSHG', index=1, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XSHE', index=2, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XHKG', index=3, number=203,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CCFX', index=4, number=301,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XSGE', index=5, number=302,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SGEX', index=6, number=401,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XCFE', index=7, number=501,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XDCE', index=8, number=601,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='XZCE', index=9, number=602,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=48,
  serialized_end=193,
)
_sym_db.RegisterEnumDescriptor(_ESECURITYIDSOURCE)

ESecurityIDSource = enum_type_wrapper.EnumTypeWrapper(_ESECURITYIDSOURCE)
DefaultSecurityIDSource = 0
XSHG = 101
XSHE = 102
XHKG = 203
CCFX = 301
XSGE = 302
SGEX = 401
XCFE = 501
XDCE = 601
XZCE = 602


DESCRIPTOR.enum_types_by_name['ESecurityIDSource'] = _ESECURITYIDSOURCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022com.htsc.mdc.modelB\027ESecurityIDSourceProtosH\001\240\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
