# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IMDTickService_pb2 as IMDTickService__pb2


class IMDTickServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getMDSecurityTick = channel.unary_stream(
        '/com.htsc.mdc.hawkeye.model.gservice.IMDTickService/getMDSecurityTick',
        request_serializer=IMDTickService__pb2.MDTickRpcRequest.SerializeToString,
        response_deserializer=IMDTickService__pb2.MDTickRpcResponse.FromString,
        )
    self.getMDSecurityTickByTimeOrder = channel.unary_stream(
        '/com.htsc.mdc.hawkeye.model.gservice.IMDTickService/getMDSecurityTickByTimeOrder',
        request_serializer=IMDTickService__pb2.MDTickTimeOrderRpcRequest.SerializeToString,
        response_deserializer=IMDTickService__pb2.MDTickRpcResponse.FromString,
        )
    self.queryMDMaxPriceAndMinPrice = channel.unary_unary(
        '/com.htsc.mdc.hawkeye.model.gservice.IMDTickService/queryMDMaxPriceAndMinPrice',
        request_serializer=IMDTickService__pb2.MDTickMaxPriceAndMinPriceRequest.SerializeToString,
        response_deserializer=IMDTickService__pb2.MDTickMaxPriceAndMinPriceResponse.FromString,
        )
    self.queryMDTickFor1Time = channel.unary_unary(
        '/com.htsc.mdc.hawkeye.model.gservice.IMDTickService/queryMDTickFor1Time',
        request_serializer=IMDTickService__pb2.MDTickFor1TimeRequest.SerializeToString,
        response_deserializer=IMDTickService__pb2.MDTickFor1TimeResponse.FromString,
        )
    self.getMDSecurityOrderDetail = channel.unary_stream(
        '/com.htsc.mdc.hawkeye.model.gservice.IMDTickService/getMDSecurityOrderDetail',
        request_serializer=IMDTickService__pb2.MDTickOrderDetailRpcRequest.SerializeToString,
        response_deserializer=IMDTickService__pb2.MDTickOrderDetailRpcResponse.FromString,
        )
    self.getMDSecurityOrderDetailByTimeOrder = channel.unary_stream(
        '/com.htsc.mdc.hawkeye.model.gservice.IMDTickService/getMDSecurityOrderDetailByTimeOrder',
        request_serializer=IMDTickService__pb2.MDTickOrderDetailTimeOrderRpcRequest.SerializeToString,
        response_deserializer=IMDTickService__pb2.MDTickOrderDetailRpcResponse.FromString,
        )


class IMDTickServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getMDSecurityTick(self, request, context):
    """query tick security record
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMDSecurityTickByTimeOrder(self, request, context):
    """query tick security record by MDTime Order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryMDMaxPriceAndMinPrice(self, request, context):
    """query maxPx & minPx in a time gap
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def queryMDTickFor1Time(self, request, context):
    """query one latest tick
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMDSecurityOrderDetail(self, request, context):
    """query OrderDetail
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMDSecurityOrderDetailByTimeOrder(self, request, context):
    """query OrderDetail by MDTime Order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IMDTickServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getMDSecurityTick': grpc.unary_stream_rpc_method_handler(
          servicer.getMDSecurityTick,
          request_deserializer=IMDTickService__pb2.MDTickRpcRequest.FromString,
          response_serializer=IMDTickService__pb2.MDTickRpcResponse.SerializeToString,
      ),
      'getMDSecurityTickByTimeOrder': grpc.unary_stream_rpc_method_handler(
          servicer.getMDSecurityTickByTimeOrder,
          request_deserializer=IMDTickService__pb2.MDTickTimeOrderRpcRequest.FromString,
          response_serializer=IMDTickService__pb2.MDTickRpcResponse.SerializeToString,
      ),
      'queryMDMaxPriceAndMinPrice': grpc.unary_unary_rpc_method_handler(
          servicer.queryMDMaxPriceAndMinPrice,
          request_deserializer=IMDTickService__pb2.MDTickMaxPriceAndMinPriceRequest.FromString,
          response_serializer=IMDTickService__pb2.MDTickMaxPriceAndMinPriceResponse.SerializeToString,
      ),
      'queryMDTickFor1Time': grpc.unary_unary_rpc_method_handler(
          servicer.queryMDTickFor1Time,
          request_deserializer=IMDTickService__pb2.MDTickFor1TimeRequest.FromString,
          response_serializer=IMDTickService__pb2.MDTickFor1TimeResponse.SerializeToString,
      ),
      'getMDSecurityOrderDetail': grpc.unary_stream_rpc_method_handler(
          servicer.getMDSecurityOrderDetail,
          request_deserializer=IMDTickService__pb2.MDTickOrderDetailRpcRequest.FromString,
          response_serializer=IMDTickService__pb2.MDTickOrderDetailRpcResponse.SerializeToString,
      ),
      'getMDSecurityOrderDetailByTimeOrder': grpc.unary_stream_rpc_method_handler(
          servicer.getMDSecurityOrderDetailByTimeOrder,
          request_deserializer=IMDTickService__pb2.MDTickOrderDetailTimeOrderRpcRequest.FromString,
          response_serializer=IMDTickService__pb2.MDTickOrderDetailRpcResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.htsc.mdc.hawkeye.model.gservice.IMDTickService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
