# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IMDTransactionService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import InsightErrorContext_pb2 as InsightErrorContext__pb2
import MarketData_pb2 as MarketData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IMDTransactionService.proto',
  package='com.htsc.mdc.hawkeye.model.gservice',
  syntax='proto3',
  serialized_pb=_b('\n\x1bIMDTransactionService.proto\x12#com.htsc.mdc.hawkeye.model.gservice\x1a\x19InsightErrorContext.proto\x1a\x10MarketData.proto\"V\n\x17MDTransactionRpcRequest\x12\x16\n\x0ehtscSecurityID\x18\x01 \x01(\t\x12\x11\n\tstartTime\x18\x02 \x01(\t\x12\x10\n\x08stopTime\x18\x03 \x01(\t\"q\n MDTransactionTimeOrderRpcRequest\x12\x16\n\x0ehtscSecurityID\x18\x01 \x01(\t\x12\x11\n\tstartTime\x18\x02 \x01(\t\x12\x10\n\x08stopTime\x18\x03 \x01(\t\x12\x10\n\x08\x61scOrder\x18\x04 \x01(\x08\"\xb3\x01\n\x18MDTransactionRpcResponse\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x12L\n\x13insightErrorContext\x18\x02 \x01(\x0b\x32/.com.htsc.mdc.hawkeye.model.InsightErrorContext\x12\x36\n\x06result\x18\x03 \x01(\x0b\x32&.com.htsc.mdc.hawkeye.model.MarketData2\xd7\x02\n\x15IMDTransactionService\x12\x93\x01\n\x10getMDTransaction\x12<.com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcRequest\x1a=.com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcResponse\"\x00\x30\x01\x12\xa7\x01\n\x1bgetMDTransactionByTimeOrder\x12\x45.com.htsc.mdc.hawkeye.model.gservice.MDTransactionTimeOrderRpcRequest\x1a=.com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcResponse\"\x00\x30\x01\x42O\n#com.htsc.mdc.hawkeye.model.gserviceB\x1bIMDTransactionServiceProtosH\x01P\x01\xa0\x01\x01\xa2\x02\x03RTGb\x06proto3')
  ,
  dependencies=[InsightErrorContext__pb2.DESCRIPTOR,MarketData__pb2.DESCRIPTOR,])




_MDTRANSACTIONRPCREQUEST = _descriptor.Descriptor(
  name='MDTransactionRpcRequest',
  full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='htscSecurityID', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcRequest.htscSecurityID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcRequest.startTime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stopTime', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcRequest.stopTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=199,
)


_MDTRANSACTIONTIMEORDERRPCREQUEST = _descriptor.Descriptor(
  name='MDTransactionTimeOrderRpcRequest',
  full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionTimeOrderRpcRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='htscSecurityID', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionTimeOrderRpcRequest.htscSecurityID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionTimeOrderRpcRequest.startTime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stopTime', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionTimeOrderRpcRequest.stopTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ascOrder', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionTimeOrderRpcRequest.ascOrder', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=314,
)


_MDTRANSACTIONRPCRESPONSE = _descriptor.Descriptor(
  name='MDTransactionRpcResponse',
  full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcResponse.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='insightErrorContext', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcResponse.insightErrorContext', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcResponse.result', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=496,
)

_MDTRANSACTIONRPCRESPONSE.fields_by_name['insightErrorContext'].message_type = InsightErrorContext__pb2._INSIGHTERRORCONTEXT
_MDTRANSACTIONRPCRESPONSE.fields_by_name['result'].message_type = MarketData__pb2._MARKETDATA
DESCRIPTOR.message_types_by_name['MDTransactionRpcRequest'] = _MDTRANSACTIONRPCREQUEST
DESCRIPTOR.message_types_by_name['MDTransactionTimeOrderRpcRequest'] = _MDTRANSACTIONTIMEORDERRPCREQUEST
DESCRIPTOR.message_types_by_name['MDTransactionRpcResponse'] = _MDTRANSACTIONRPCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDTransactionRpcRequest = _reflection.GeneratedProtocolMessageType('MDTransactionRpcRequest', (_message.Message,), dict(
  DESCRIPTOR = _MDTRANSACTIONRPCREQUEST,
  __module__ = 'IMDTransactionService_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcRequest)
  ))
_sym_db.RegisterMessage(MDTransactionRpcRequest)

MDTransactionTimeOrderRpcRequest = _reflection.GeneratedProtocolMessageType('MDTransactionTimeOrderRpcRequest', (_message.Message,), dict(
  DESCRIPTOR = _MDTRANSACTIONTIMEORDERRPCREQUEST,
  __module__ = 'IMDTransactionService_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.gservice.MDTransactionTimeOrderRpcRequest)
  ))
_sym_db.RegisterMessage(MDTransactionTimeOrderRpcRequest)

MDTransactionRpcResponse = _reflection.GeneratedProtocolMessageType('MDTransactionRpcResponse', (_message.Message,), dict(
  DESCRIPTOR = _MDTRANSACTIONRPCRESPONSE,
  __module__ = 'IMDTransactionService_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.gservice.MDTransactionRpcResponse)
  ))
_sym_db.RegisterMessage(MDTransactionRpcResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.htsc.mdc.hawkeye.model.gserviceB\033IMDTransactionServiceProtosH\001P\001\240\001\001\242\002\003RTG'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class IMDTransactionServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.getMDTransaction = channel.unary_stream(
          '/com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService/getMDTransaction',
          request_serializer=MDTransactionRpcRequest.SerializeToString,
          response_deserializer=MDTransactionRpcResponse.FromString,
          )
      self.getMDTransactionByTimeOrder = channel.unary_stream(
          '/com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService/getMDTransactionByTimeOrder',
          request_serializer=MDTransactionTimeOrderRpcRequest.SerializeToString,
          response_deserializer=MDTransactionRpcResponse.FromString,
          )


  class IMDTransactionServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def getMDTransaction(self, request, context):
      """query MDTransaction
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def getMDTransactionByTimeOrder(self, request, context):
      """query MDTransaction by MDTime Order
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_IMDTransactionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'getMDTransaction': grpc.unary_stream_rpc_method_handler(
            servicer.getMDTransaction,
            request_deserializer=MDTransactionRpcRequest.FromString,
            response_serializer=MDTransactionRpcResponse.SerializeToString,
        ),
        'getMDTransactionByTimeOrder': grpc.unary_stream_rpc_method_handler(
            servicer.getMDTransactionByTimeOrder,
            request_deserializer=MDTransactionTimeOrderRpcRequest.FromString,
            response_serializer=MDTransactionRpcResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaIMDTransactionServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def getMDTransaction(self, request, context):
      """query MDTransaction
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def getMDTransactionByTimeOrder(self, request, context):
      """query MDTransaction by MDTime Order
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaIMDTransactionServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def getMDTransaction(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """query MDTransaction
      """
      raise NotImplementedError()
    def getMDTransactionByTimeOrder(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """query MDTransaction by MDTime Order
      """
      raise NotImplementedError()


  def beta_create_IMDTransactionService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransaction'): MDTransactionRpcRequest.FromString,
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransactionByTimeOrder'): MDTransactionTimeOrderRpcRequest.FromString,
    }
    response_serializers = {
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransaction'): MDTransactionRpcResponse.SerializeToString,
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransactionByTimeOrder'): MDTransactionRpcResponse.SerializeToString,
    }
    method_implementations = {
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransaction'): face_utilities.unary_stream_inline(servicer.getMDTransaction),
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransactionByTimeOrder'): face_utilities.unary_stream_inline(servicer.getMDTransactionByTimeOrder),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_IMDTransactionService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransaction'): MDTransactionRpcRequest.SerializeToString,
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransactionByTimeOrder'): MDTransactionTimeOrderRpcRequest.SerializeToString,
    }
    response_deserializers = {
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransaction'): MDTransactionRpcResponse.FromString,
      ('com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', 'getMDTransactionByTimeOrder'): MDTransactionRpcResponse.FromString,
    }
    cardinalities = {
      'getMDTransaction': cardinality.Cardinality.UNARY_STREAM,
      'getMDTransactionByTimeOrder': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'com.htsc.mdc.hawkeye.model.gservice.IMDTransactionService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
