# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDAdjustFactor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDAdjustFactor.proto',
  package='com.htsc.mdc.model',
  syntax='proto3',
  serialized_pb=_b('\n\x14MDAdjustFactor.proto\x12\x12\x63om.htsc.mdc.model\"\xa1\x01\n\x0eMDAdjustFactor\x12\x16\n\x0ehtscSecurityID\x18\x01 \x01(\t\x12\x11\n\tbeginDate\x18\x02 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x03 \x01(\t\x12\x0b\n\x03xdy\x18\x04 \x01(\x01\x12\x0e\n\x06ltdXdy\x18\x05 \x01(\x01\x12\x12\n\ndataSource\x18\x06 \x01(\t\x12\x11\n\ttheLtdXdy\x18\x07 \x01(\x01\x12\x0f\n\x07isValid\x18\x08 \x01(\x08\x42.\n\x12\x63om.htsc.mdc.modelB\x13MDAdjustFactorProtoH\x01\xa0\x01\x01\x62\x06proto3')
)




_MDADJUSTFACTOR = _descriptor.Descriptor(
  name='MDAdjustFactor',
  full_name='com.htsc.mdc.model.MDAdjustFactor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='htscSecurityID', full_name='com.htsc.mdc.model.MDAdjustFactor.htscSecurityID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beginDate', full_name='com.htsc.mdc.model.MDAdjustFactor.beginDate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endDate', full_name='com.htsc.mdc.model.MDAdjustFactor.endDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='xdy', full_name='com.htsc.mdc.model.MDAdjustFactor.xdy', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ltdXdy', full_name='com.htsc.mdc.model.MDAdjustFactor.ltdXdy', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataSource', full_name='com.htsc.mdc.model.MDAdjustFactor.dataSource', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='theLtdXdy', full_name='com.htsc.mdc.model.MDAdjustFactor.theLtdXdy', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isValid', full_name='com.htsc.mdc.model.MDAdjustFactor.isValid', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=206,
)

DESCRIPTOR.message_types_by_name['MDAdjustFactor'] = _MDADJUSTFACTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDAdjustFactor = _reflection.GeneratedProtocolMessageType('MDAdjustFactor', (_message.Message,), dict(
  DESCRIPTOR = _MDADJUSTFACTOR,
  __module__ = 'MDAdjustFactor_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.model.MDAdjustFactor)
  ))
_sym_db.RegisterMessage(MDAdjustFactor)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022com.htsc.mdc.modelB\023MDAdjustFactorProtoH\001\240\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
