# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDConstantRecord.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ESecurityType_pb2 as ESecurityType__pb2
import ESecurityIDSource_pb2 as ESecurityIDSource__pb2
import EMDLevel_pb2 as EMDLevel__pb2
import EMDChannel_pb2 as EMDChannel__pb2
import SwitchStatus_pb2 as SwitchStatus__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDConstantRecord.proto',
  package='com.htsc.mdc.model',
  syntax='proto3',
  serialized_pb=_b('\n\x16MDConstantRecord.proto\x12\x12\x63om.htsc.mdc.model\x1a\x13\x45SecurityType.proto\x1a\x17\x45SecurityIDSource.proto\x1a\x0e\x45MDLevel.proto\x1a\x10\x45MDChannel.proto\x1a\x12SwitchStatus.proto\"\x99\x05\n\x10MDConstantRecord\x12\x14\n\x0cMDConstantID\x18\x01 \x01(\t\x12\x12\n\nMDReportID\x18\x02 \x01(\t\x12\x0e\n\x06MDDate\x18\x03 \x01(\t\x12\x0e\n\x06MDTime\x18\x04 \x01(\t\x12\x12\n\nMDStreamID\x18\x05 \x01(\t\x12\x37\n\x0cSecurityType\x18\x06 \x01(\x0e\x32!.com.htsc.mdc.model.ESecurityType\x12\x17\n\x0fSecuritySubType\x18\x07 \x01(\t\x12\x12\n\nSecurityID\x18\x08 \x01(\t\x12?\n\x10SecurityIDSource\x18\t \x01(\x0e\x32%.com.htsc.mdc.model.ESecurityIDSource\x12\x0e\n\x06Symbol\x18\n \x01(\t\x12-\n\x07MDLevel\x18\x0b \x01(\x0e\x32\x1c.com.htsc.mdc.model.EMDLevel\x12\x31\n\tMDChannel\x18\x0c \x01(\x0e\x32\x1e.com.htsc.mdc.model.EMDChannel\x12\x18\n\x10TradingPhaseCode\x18\r \x01(\t\x12\x16\n\x0eHTSCSecurityID\x18\x0e \x01(\t\x12>\n\x14\x43onstantSwitchStatus\x18\x0f \x03(\x0b\x32 .com.htsc.mdc.model.SwitchStatus\x12\x10\n\x08ListDate\x18\x10 \x01(\t\x12\x10\n\x08\x43urrency\x18\x11 \x01(\t\x12\x12\n\nPreClosePx\x18\x12 \x01(\x01\x12\x18\n\x10OutstandingShare\x18\x13 \x01(\x01\x12 \n\x18PublicFloatShareQuantity\x18\x14 \x01(\x01\x12\x13\n\x0b\x43hiSpelling\x18\x15 \x01(\t\x12\x13\n\x0b\x45nglishName\x18\x16 \x01(\tB1\n\x12\x63om.htsc.mdc.modelB\x16MDConstantRecordProtosH\x01\xa0\x01\x01\x62\x06proto3')
  ,
  dependencies=[ESecurityType__pb2.DESCRIPTOR,ESecurityIDSource__pb2.DESCRIPTOR,EMDLevel__pb2.DESCRIPTOR,EMDChannel__pb2.DESCRIPTOR,SwitchStatus__pb2.DESCRIPTOR,])




_MDCONSTANTRECORD = _descriptor.Descriptor(
  name='MDConstantRecord',
  full_name='com.htsc.mdc.model.MDConstantRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MDConstantID', full_name='com.htsc.mdc.model.MDConstantRecord.MDConstantID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDReportID', full_name='com.htsc.mdc.model.MDConstantRecord.MDReportID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDDate', full_name='com.htsc.mdc.model.MDConstantRecord.MDDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDTime', full_name='com.htsc.mdc.model.MDConstantRecord.MDTime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDStreamID', full_name='com.htsc.mdc.model.MDConstantRecord.MDStreamID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SecurityType', full_name='com.htsc.mdc.model.MDConstantRecord.SecurityType', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SecuritySubType', full_name='com.htsc.mdc.model.MDConstantRecord.SecuritySubType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SecurityID', full_name='com.htsc.mdc.model.MDConstantRecord.SecurityID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SecurityIDSource', full_name='com.htsc.mdc.model.MDConstantRecord.SecurityIDSource', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Symbol', full_name='com.htsc.mdc.model.MDConstantRecord.Symbol', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDLevel', full_name='com.htsc.mdc.model.MDConstantRecord.MDLevel', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDChannel', full_name='com.htsc.mdc.model.MDConstantRecord.MDChannel', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TradingPhaseCode', full_name='com.htsc.mdc.model.MDConstantRecord.TradingPhaseCode', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HTSCSecurityID', full_name='com.htsc.mdc.model.MDConstantRecord.HTSCSecurityID', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ConstantSwitchStatus', full_name='com.htsc.mdc.model.MDConstantRecord.ConstantSwitchStatus', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ListDate', full_name='com.htsc.mdc.model.MDConstantRecord.ListDate', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Currency', full_name='com.htsc.mdc.model.MDConstantRecord.Currency', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PreClosePx', full_name='com.htsc.mdc.model.MDConstantRecord.PreClosePx', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OutstandingShare', full_name='com.htsc.mdc.model.MDConstantRecord.OutstandingShare', index=18,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PublicFloatShareQuantity', full_name='com.htsc.mdc.model.MDConstantRecord.PublicFloatShareQuantity', index=19,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChiSpelling', full_name='com.htsc.mdc.model.MDConstantRecord.ChiSpelling', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EnglishName', full_name='com.htsc.mdc.model.MDConstantRecord.EnglishName', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=812,
)

_MDCONSTANTRECORD.fields_by_name['SecurityType'].enum_type = ESecurityType__pb2._ESECURITYTYPE
_MDCONSTANTRECORD.fields_by_name['SecurityIDSource'].enum_type = ESecurityIDSource__pb2._ESECURITYIDSOURCE
_MDCONSTANTRECORD.fields_by_name['MDLevel'].enum_type = EMDLevel__pb2._EMDLEVEL
_MDCONSTANTRECORD.fields_by_name['MDChannel'].enum_type = EMDChannel__pb2._EMDCHANNEL
_MDCONSTANTRECORD.fields_by_name['ConstantSwitchStatus'].message_type = SwitchStatus__pb2._SWITCHSTATUS
DESCRIPTOR.message_types_by_name['MDConstantRecord'] = _MDCONSTANTRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDConstantRecord = _reflection.GeneratedProtocolMessageType('MDConstantRecord', (_message.Message,), dict(
  DESCRIPTOR = _MDCONSTANTRECORD,
  __module__ = 'MDConstantRecord_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.model.MDConstantRecord)
  ))
_sym_db.RegisterMessage(MDConstantRecord)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022com.htsc.mdc.modelB\026MDConstantRecordProtosH\001\240\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
