# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDForexRecord.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ESecurityType_pb2 as ESecurityType__pb2
import ESecurityIDSource_pb2 as ESecurityIDSource__pb2
import EMDChannel_pb2 as EMDChannel__pb2
import EMDRecordType_pb2 as EMDRecordType__pb2
import EMDValidType_pb2 as EMDValidType__pb2
import EMDLevel_pb2 as EMDLevel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDForexRecord.proto',
  package='com.htsc.mdc.model',
  syntax='proto3',
  serialized_pb=_b('\n\x13MDForexRecord.proto\x12\x12\x63om.htsc.mdc.model\x1a\x13\x45SecurityType.proto\x1a\x17\x45SecurityIDSource.proto\x1a\x10\x45MDChannel.proto\x1a\x13\x45MDRecordType.proto\x1a\x12\x45MDValidType.proto\x1a\x0e\x45MDLevel.proto\"\xfe\x06\n\rMDForexRecord\x12\x12\n\nMDRecordID\x18\x01 \x01(\t\x12\x12\n\nMDReportID\x18\x02 \x01(\t\x12\x0e\n\x06MDDate\x18\x03 \x01(\t\x12\x0e\n\x06MDTime\x18\x04 \x01(\t\x12\x12\n\nMDStreamID\x18\x05 \x01(\t\x12\x37\n\x0cSecurityType\x18\x06 \x01(\x0e\x32!.com.htsc.mdc.model.ESecurityType\x12\x17\n\x0fSecuritySubType\x18\x07 \x01(\t\x12\x12\n\nSecurityID\x18\x08 \x01(\t\x12?\n\x10SecurityIDSource\x18\t \x01(\x0e\x32%.com.htsc.mdc.model.ESecurityIDSource\x12\x0e\n\x06Symbol\x18\n \x01(\t\x12-\n\x07MDLevel\x18\x0b \x01(\x0e\x32\x1c.com.htsc.mdc.model.EMDLevel\x12\x31\n\tMDChannel\x18\x0c \x01(\x0e\x32\x1e.com.htsc.mdc.model.EMDChannel\x12\x18\n\x10TradingPhaseCode\x18\r \x01(\t\x12\x37\n\x0cMDRecordType\x18\x0e \x01(\x0e\x32!.com.htsc.mdc.model.EMDRecordType\x12\x16\n\x0eHTSCSecurityID\x18\x0f \x01(\t\x12\x17\n\x0fReceiveDateTime\x18\x10 \x01(\x03\x12\x35\n\x0bMDValidType\x18\x11 \x01(\x0e\x32 .com.htsc.mdc.model.EMDValidType\x12\x12\n\nPreClosePx\x18\x12 \x01(\x01\x12\x18\n\x10TotalVolumeTrade\x18\x13 \x01(\x01\x12\x17\n\x0fTotalValueTrade\x18\x14 \x01(\x01\x12\x0e\n\x06LastPx\x18\x15 \x01(\x01\x12\x0e\n\x06OpenPx\x18\x16 \x01(\x01\x12\x0f\n\x07\x43losePx\x18\x17 \x01(\x01\x12\x0e\n\x06HighPx\x18\x18 \x01(\x01\x12\r\n\x05LowPx\x18\x19 \x01(\x01\x12\x11\n\tBuy1Price\x18\x1a \x01(\x01\x12\x14\n\x0c\x42uy1OrderQty\x18\x1b \x01(\x01\x12\x12\n\nSell1Price\x18\x1c \x01(\x01\x12\x15\n\rSell1OrderQty\x18\x1d \x01(\x01\x12\r\n\x05MidPx\x18\x1e \x01(\x01\x12\x14\n\x0c\x45xchangeDate\x18\x1f \x01(\t\x12\x14\n\x0c\x45xchangeTime\x18  \x01(\t\x12\x17\n\x0f\x41rrivalDateTime\x18! \x01(\x03\x42.\n\x12\x63om.htsc.mdc.modelB\x13MDForexRecordProtosH\x01\xa0\x01\x01\x62\x06proto3')
  ,
  dependencies=[ESecurityType__pb2.DESCRIPTOR,ESecurityIDSource__pb2.DESCRIPTOR,EMDChannel__pb2.DESCRIPTOR,EMDRecordType__pb2.DESCRIPTOR,EMDValidType__pb2.DESCRIPTOR,EMDLevel__pb2.DESCRIPTOR,])




_MDFOREXRECORD = _descriptor.Descriptor(
  name='MDForexRecord',
  full_name='com.htsc.mdc.model.MDForexRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MDRecordID', full_name='com.htsc.mdc.model.MDForexRecord.MDRecordID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDReportID', full_name='com.htsc.mdc.model.MDForexRecord.MDReportID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDDate', full_name='com.htsc.mdc.model.MDForexRecord.MDDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDTime', full_name='com.htsc.mdc.model.MDForexRecord.MDTime', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDStreamID', full_name='com.htsc.mdc.model.MDForexRecord.MDStreamID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecurityType', full_name='com.htsc.mdc.model.MDForexRecord.SecurityType', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecuritySubType', full_name='com.htsc.mdc.model.MDForexRecord.SecuritySubType', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecurityID', full_name='com.htsc.mdc.model.MDForexRecord.SecurityID', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecurityIDSource', full_name='com.htsc.mdc.model.MDForexRecord.SecurityIDSource', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Symbol', full_name='com.htsc.mdc.model.MDForexRecord.Symbol', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDLevel', full_name='com.htsc.mdc.model.MDForexRecord.MDLevel', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDChannel', full_name='com.htsc.mdc.model.MDForexRecord.MDChannel', index=11,
      number=12, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TradingPhaseCode', full_name='com.htsc.mdc.model.MDForexRecord.TradingPhaseCode', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDRecordType', full_name='com.htsc.mdc.model.MDForexRecord.MDRecordType', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HTSCSecurityID', full_name='com.htsc.mdc.model.MDForexRecord.HTSCSecurityID', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ReceiveDateTime', full_name='com.htsc.mdc.model.MDForexRecord.ReceiveDateTime', index=15,
      number=16, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDValidType', full_name='com.htsc.mdc.model.MDForexRecord.MDValidType', index=16,
      number=17, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PreClosePx', full_name='com.htsc.mdc.model.MDForexRecord.PreClosePx', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TotalVolumeTrade', full_name='com.htsc.mdc.model.MDForexRecord.TotalVolumeTrade', index=18,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='TotalValueTrade', full_name='com.htsc.mdc.model.MDForexRecord.TotalValueTrade', index=19,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LastPx', full_name='com.htsc.mdc.model.MDForexRecord.LastPx', index=20,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OpenPx', full_name='com.htsc.mdc.model.MDForexRecord.OpenPx', index=21,
      number=22, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ClosePx', full_name='com.htsc.mdc.model.MDForexRecord.ClosePx', index=22,
      number=23, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HighPx', full_name='com.htsc.mdc.model.MDForexRecord.HighPx', index=23,
      number=24, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LowPx', full_name='com.htsc.mdc.model.MDForexRecord.LowPx', index=24,
      number=25, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Buy1Price', full_name='com.htsc.mdc.model.MDForexRecord.Buy1Price', index=25,
      number=26, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Buy1OrderQty', full_name='com.htsc.mdc.model.MDForexRecord.Buy1OrderQty', index=26,
      number=27, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sell1Price', full_name='com.htsc.mdc.model.MDForexRecord.Sell1Price', index=27,
      number=28, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sell1OrderQty', full_name='com.htsc.mdc.model.MDForexRecord.Sell1OrderQty', index=28,
      number=29, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MidPx', full_name='com.htsc.mdc.model.MDForexRecord.MidPx', index=29,
      number=30, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ExchangeDate', full_name='com.htsc.mdc.model.MDForexRecord.ExchangeDate', index=30,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ExchangeTime', full_name='com.htsc.mdc.model.MDForexRecord.ExchangeTime', index=31,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ArrivalDateTime', full_name='com.htsc.mdc.model.MDForexRecord.ArrivalDateTime', index=32,
      number=33, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=1059,
)

_MDFOREXRECORD.fields_by_name['SecurityType'].enum_type = ESecurityType__pb2._ESECURITYTYPE
_MDFOREXRECORD.fields_by_name['SecurityIDSource'].enum_type = ESecurityIDSource__pb2._ESECURITYIDSOURCE
_MDFOREXRECORD.fields_by_name['MDLevel'].enum_type = EMDLevel__pb2._EMDLEVEL
_MDFOREXRECORD.fields_by_name['MDChannel'].enum_type = EMDChannel__pb2._EMDCHANNEL
_MDFOREXRECORD.fields_by_name['MDRecordType'].enum_type = EMDRecordType__pb2._EMDRECORDTYPE
_MDFOREXRECORD.fields_by_name['MDValidType'].enum_type = EMDValidType__pb2._EMDVALIDTYPE
DESCRIPTOR.message_types_by_name['MDForexRecord'] = _MDFOREXRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDForexRecord = _reflection.GeneratedProtocolMessageType('MDForexRecord', (_message.Message,), dict(
  DESCRIPTOR = _MDFOREXRECORD,
  __module__ = 'MDForexRecord_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.model.MDForexRecord)
  ))
_sym_db.RegisterMessage(MDForexRecord)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022com.htsc.mdc.modelB\023MDForexRecordProtosH\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
