# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDQuoteRecord.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ESecurityType_pb2 as ESecurityType__pb2
import ESecurityIDSource_pb2 as ESecurityIDSource__pb2
import EMDLevel_pb2 as EMDLevel__pb2
import EMDChannel_pb2 as EMDChannel__pb2
import EMDRecordType_pb2 as EMDRecordType__pb2
import EMDValidType_pb2 as EMDValidType__pb2
import CashBondQuote_pb2 as CashBondQuote__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDQuoteRecord.proto',
  package='com.htsc.mdc.model',
  syntax='proto3',
  serialized_pb=_b('\n\x13MDQuoteRecord.proto\x12\x12\x63om.htsc.mdc.model\x1a\x13\x45SecurityType.proto\x1a\x17\x45SecurityIDSource.proto\x1a\x0e\x45MDLevel.proto\x1a\x10\x45MDChannel.proto\x1a\x13\x45MDRecordType.proto\x1a\x12\x45MDValidType.proto\x1a\x13\x43\x61shBondQuote.proto\"\xe9\x05\n\rMDQuoteRecord\x12\x0e\n\x06MDDate\x18\x01 \x01(\t\x12\x0e\n\x06MDTime\x18\x02 \x01(\t\x12\x37\n\x0cSecurityType\x18\x03 \x01(\x0e\x32!.com.htsc.mdc.model.ESecurityType\x12\x17\n\x0fSecuritySubType\x18\x04 \x01(\t\x12\x12\n\nSecurityID\x18\x05 \x01(\t\x12?\n\x10SecurityIDSource\x18\x06 \x01(\x0e\x32%.com.htsc.mdc.model.ESecurityIDSource\x12\x0e\n\x06Symbol\x18\x07 \x01(\t\x12-\n\x07MDLevel\x18\x08 \x01(\x0e\x32\x1c.com.htsc.mdc.model.EMDLevel\x12\x31\n\tMDChannel\x18\t \x01(\x0e\x32\x1e.com.htsc.mdc.model.EMDChannel\x12\x37\n\x0cMDRecordType\x18\n \x01(\x0e\x32!.com.htsc.mdc.model.EMDRecordType\x12\x16\n\x0eHTSCSecurityID\x18\x0b \x01(\t\x12\x17\n\x0fReceiveDateTime\x18\x0c \x01(\x03\x12\x35\n\x0bMDValidType\x18\r \x01(\x0e\x32 .com.htsc.mdc.model.EMDValidType\x12\x12\n\nMDBookType\x18\x0e \x01(\x05\x12\x17\n\x0fMarketIndicator\x18\x0f \x01(\t\x12\x13\n\x0bMarketDepth\x18\x10 \x01(\x05\x12\x39\n\x0e\x43\x61shBondQuotes\x18\x11 \x03(\x0b\x32!.com.htsc.mdc.model.CashBondQuote\x12\x11\n\tChannelNo\x18\x12 \x01(\x05\x12\x12\n\nApplSeqNum\x18\x13 \x01(\x03\x12\x14\n\x0c\x45xchangeDate\x18\x14 \x01(\t\x12\x14\n\x0c\x45xchangeTime\x18\x15 \x01(\t\x12\x15\n\rMDSubBookType\x18\x16 \x01(\x05\x12\x17\n\x0f\x41rrivalDateTime\x18\x17 \x01(\x03\x42.\n\x12\x63om.htsc.mdc.modelB\x13MDQuoteRecordProtosH\x01\xa0\x01\x01\x62\x06proto3')
  ,
  dependencies=[ESecurityType__pb2.DESCRIPTOR,ESecurityIDSource__pb2.DESCRIPTOR,EMDLevel__pb2.DESCRIPTOR,EMDChannel__pb2.DESCRIPTOR,EMDRecordType__pb2.DESCRIPTOR,EMDValidType__pb2.DESCRIPTOR,CashBondQuote__pb2.DESCRIPTOR,])




_MDQUOTERECORD = _descriptor.Descriptor(
  name='MDQuoteRecord',
  full_name='com.htsc.mdc.model.MDQuoteRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MDDate', full_name='com.htsc.mdc.model.MDQuoteRecord.MDDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDTime', full_name='com.htsc.mdc.model.MDQuoteRecord.MDTime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecurityType', full_name='com.htsc.mdc.model.MDQuoteRecord.SecurityType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecuritySubType', full_name='com.htsc.mdc.model.MDQuoteRecord.SecuritySubType', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecurityID', full_name='com.htsc.mdc.model.MDQuoteRecord.SecurityID', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SecurityIDSource', full_name='com.htsc.mdc.model.MDQuoteRecord.SecurityIDSource', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Symbol', full_name='com.htsc.mdc.model.MDQuoteRecord.Symbol', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDLevel', full_name='com.htsc.mdc.model.MDQuoteRecord.MDLevel', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDChannel', full_name='com.htsc.mdc.model.MDQuoteRecord.MDChannel', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDRecordType', full_name='com.htsc.mdc.model.MDQuoteRecord.MDRecordType', index=9,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='HTSCSecurityID', full_name='com.htsc.mdc.model.MDQuoteRecord.HTSCSecurityID', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ReceiveDateTime', full_name='com.htsc.mdc.model.MDQuoteRecord.ReceiveDateTime', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDValidType', full_name='com.htsc.mdc.model.MDQuoteRecord.MDValidType', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDBookType', full_name='com.htsc.mdc.model.MDQuoteRecord.MDBookType', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MarketIndicator', full_name='com.htsc.mdc.model.MDQuoteRecord.MarketIndicator', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MarketDepth', full_name='com.htsc.mdc.model.MDQuoteRecord.MarketDepth', index=15,
      number=16, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CashBondQuotes', full_name='com.htsc.mdc.model.MDQuoteRecord.CashBondQuotes', index=16,
      number=17, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ChannelNo', full_name='com.htsc.mdc.model.MDQuoteRecord.ChannelNo', index=17,
      number=18, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ApplSeqNum', full_name='com.htsc.mdc.model.MDQuoteRecord.ApplSeqNum', index=18,
      number=19, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ExchangeDate', full_name='com.htsc.mdc.model.MDQuoteRecord.ExchangeDate', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ExchangeTime', full_name='com.htsc.mdc.model.MDQuoteRecord.ExchangeTime', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MDSubBookType', full_name='com.htsc.mdc.model.MDQuoteRecord.MDSubBookType', index=21,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ArrivalDateTime', full_name='com.htsc.mdc.model.MDQuoteRecord.ArrivalDateTime', index=22,
      number=23, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=931,
)

_MDQUOTERECORD.fields_by_name['SecurityType'].enum_type = ESecurityType__pb2._ESECURITYTYPE
_MDQUOTERECORD.fields_by_name['SecurityIDSource'].enum_type = ESecurityIDSource__pb2._ESECURITYIDSOURCE
_MDQUOTERECORD.fields_by_name['MDLevel'].enum_type = EMDLevel__pb2._EMDLEVEL
_MDQUOTERECORD.fields_by_name['MDChannel'].enum_type = EMDChannel__pb2._EMDCHANNEL
_MDQUOTERECORD.fields_by_name['MDRecordType'].enum_type = EMDRecordType__pb2._EMDRECORDTYPE
_MDQUOTERECORD.fields_by_name['MDValidType'].enum_type = EMDValidType__pb2._EMDVALIDTYPE
_MDQUOTERECORD.fields_by_name['CashBondQuotes'].message_type = CashBondQuote__pb2._CASHBONDQUOTE
DESCRIPTOR.message_types_by_name['MDQuoteRecord'] = _MDQUOTERECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDQuoteRecord = _reflection.GeneratedProtocolMessageType('MDQuoteRecord', (_message.Message,), dict(
  DESCRIPTOR = _MDQUOTERECORD,
  __module__ = 'MDQuoteRecord_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.model.MDQuoteRecord)
  ))
_sym_db.RegisterMessage(MDQuoteRecord)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022com.htsc.mdc.modelB\023MDQuoteRecordProtosH\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
