# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDQuery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SecuritySourceType_pb2 as SecuritySourceType__pb2
import InsightErrorContext_pb2 as InsightErrorContext__pb2
import MarketData_pb2 as MarketData__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDQuery.proto',
  package='com.htsc.mdc.hawkeye.model',
  syntax='proto3',
  serialized_pb=_b('\n\rMDQuery.proto\x12\x1a\x63om.htsc.mdc.hawkeye.model\x1a\x18SecuritySourceType.proto\x1a\x19InsightErrorContext.proto\x1a\x10MarketData.proto\"\xc5\x01\n\x0eMDQueryRequest\x12\x11\n\tqueryType\x18\x01 \x01(\x05\x12J\n\x12securitySourceType\x18\x02 \x03(\x0b\x32..com.htsc.mdc.hawkeye.model.SecuritySourceType\x12\x17\n\x0fhtscSecurityIDs\x18\x03 \x03(\t\x12;\n\x0bqueryParams\x18\x04 \x03(\x0b\x32&.com.htsc.mdc.hawkeye.model.QueryParam\"3\n\nQueryParam\x12\x11\n\tparamType\x18\x01 \x01(\t\x12\x12\n\nparamValue\x18\x02 \x01(\t\"\xc6\x01\n\x0fMDQueryResponse\x12\x11\n\tqueryType\x18\x01 \x01(\x05\x12\x11\n\tisSuccess\x18\x02 \x01(\x08\x12\x45\n\x0c\x65rrorContext\x18\x03 \x01(\x0b\x32/.com.htsc.mdc.hawkeye.model.InsightErrorContext\x12\x46\n\x10marketDataStream\x18\x04 \x01(\x0b\x32,.com.htsc.mdc.hawkeye.model.MarketDataStreamB/\n\x1a\x63om.htsc.mdc.hawkeye.modelB\x0cMDQueryProtoH\x01\xa0\x01\x01\x62\x06proto3')
  ,
  dependencies=[SecuritySourceType__pb2.DESCRIPTOR,InsightErrorContext__pb2.DESCRIPTOR,MarketData__pb2.DESCRIPTOR,])




_MDQUERYREQUEST = _descriptor.Descriptor(
  name='MDQueryRequest',
  full_name='com.htsc.mdc.hawkeye.model.MDQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queryType', full_name='com.htsc.mdc.hawkeye.model.MDQueryRequest.queryType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='securitySourceType', full_name='com.htsc.mdc.hawkeye.model.MDQueryRequest.securitySourceType', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='htscSecurityIDs', full_name='com.htsc.mdc.hawkeye.model.MDQueryRequest.htscSecurityIDs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='queryParams', full_name='com.htsc.mdc.hawkeye.model.MDQueryRequest.queryParams', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=314,
)


_QUERYPARAM = _descriptor.Descriptor(
  name='QueryParam',
  full_name='com.htsc.mdc.hawkeye.model.QueryParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paramType', full_name='com.htsc.mdc.hawkeye.model.QueryParam.paramType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramValue', full_name='com.htsc.mdc.hawkeye.model.QueryParam.paramValue', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=367,
)


_MDQUERYRESPONSE = _descriptor.Descriptor(
  name='MDQueryResponse',
  full_name='com.htsc.mdc.hawkeye.model.MDQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='queryType', full_name='com.htsc.mdc.hawkeye.model.MDQueryResponse.queryType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='com.htsc.mdc.hawkeye.model.MDQueryResponse.isSuccess', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorContext', full_name='com.htsc.mdc.hawkeye.model.MDQueryResponse.errorContext', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marketDataStream', full_name='com.htsc.mdc.hawkeye.model.MDQueryResponse.marketDataStream', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=568,
)

_MDQUERYREQUEST.fields_by_name['securitySourceType'].message_type = SecuritySourceType__pb2._SECURITYSOURCETYPE
_MDQUERYREQUEST.fields_by_name['queryParams'].message_type = _QUERYPARAM
_MDQUERYRESPONSE.fields_by_name['errorContext'].message_type = InsightErrorContext__pb2._INSIGHTERRORCONTEXT
_MDQUERYRESPONSE.fields_by_name['marketDataStream'].message_type = MarketData__pb2._MARKETDATASTREAM
DESCRIPTOR.message_types_by_name['MDQueryRequest'] = _MDQUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryParam'] = _QUERYPARAM
DESCRIPTOR.message_types_by_name['MDQueryResponse'] = _MDQUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDQueryRequest = _reflection.GeneratedProtocolMessageType('MDQueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _MDQUERYREQUEST,
  __module__ = 'MDQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.MDQueryRequest)
  ))
_sym_db.RegisterMessage(MDQueryRequest)

QueryParam = _reflection.GeneratedProtocolMessageType('QueryParam', (_message.Message,), dict(
  DESCRIPTOR = _QUERYPARAM,
  __module__ = 'MDQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.QueryParam)
  ))
_sym_db.RegisterMessage(QueryParam)

MDQueryResponse = _reflection.GeneratedProtocolMessageType('MDQueryResponse', (_message.Message,), dict(
  DESCRIPTOR = _MDQUERYRESPONSE,
  __module__ = 'MDQuery_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.MDQueryResponse)
  ))
_sym_db.RegisterMessage(MDQueryResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.htsc.mdc.hawkeye.modelB\014MDQueryProtoH\001\240\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
