# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDSubscribe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SecuritySourceType_pb2 as SecuritySourceType__pb2
import EMarketDataType_pb2 as EMarketDataType__pb2
import InsightErrorContext_pb2 as InsightErrorContext__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDSubscribe.proto',
  package='com.htsc.mdc.hawkeye.model',
  syntax='proto3',
  serialized_pb=_b('\n\x11MDSubscribe.proto\x12\x1a\x63om.htsc.mdc.hawkeye.model\x1a\x18SecuritySourceType.proto\x1a\x15\x45MarketDataType.proto\x1a\x19InsightErrorContext.proto\"\xb7\x02\n\x12MDSubscribeRequest\x12M\n\x13subscribeActionType\x18\x01 \x01(\x0e\x32\x30.com.htsc.mdc.hawkeye.model.ESubscribeActionType\x12>\n\x0csubscribeAll\x18\x02 \x01(\x0b\x32(.com.htsc.mdc.hawkeye.model.SubscribeAll\x12P\n\x15subscribeBySourceType\x18\x03 \x01(\x0b\x32\x31.com.htsc.mdc.hawkeye.model.SubscribeBySourceType\x12@\n\rsubscribeByID\x18\x04 \x01(\x0b\x32).com.htsc.mdc.hawkeye.model.SubscribeByID\"T\n\x0cSubscribeAll\x12\x44\n\x0fmarketDataTypes\x18\x01 \x03(\x0e\x32+.com.htsc.mdc.hawkeye.model.EMarketDataType\"\xaa\x01\n\rSubscribeByID\x12M\n\x14subscribeByIDDetails\x18\x01 \x03(\x0b\x32/.com.htsc.mdc.hawkeye.model.SubscribeByIDDetail\x12J\n\x15globalMarketDataTypes\x18\x02 \x03(\x0e\x32+.com.htsc.mdc.hawkeye.model.EMarketDataType\"s\n\x13SubscribeByIDDetail\x12\x16\n\x0ehtscSecurityID\x18\x01 \x01(\t\x12\x44\n\x0fmarketDataTypes\x18\x02 \x03(\x0e\x32+.com.htsc.mdc.hawkeye.model.EMarketDataType\"u\n\x15SubscribeBySourceType\x12\\\n\x1bsubscribeBySourceTypeDetail\x18\x01 \x03(\x0b\x32\x37.com.htsc.mdc.hawkeye.model.SubscribeBySourceTypeDetail\"\xb0\x01\n\x1bSubscribeBySourceTypeDetail\x12K\n\x13securitySourceTypes\x18\x01 \x01(\x0b\x32..com.htsc.mdc.hawkeye.model.SecuritySourceType\x12\x44\n\x0fmarketDataTypes\x18\x02 \x03(\x0e\x32+.com.htsc.mdc.hawkeye.model.EMarketDataType\"o\n\x13MDSubscribeResponse\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x12\x45\n\x0c\x65rrorContext\x18\x02 \x01(\x0b\x32/.com.htsc.mdc.hawkeye.model.InsightErrorContext*G\n\x14\x45SubscribeActionType\x12\x0c\n\x08\x43OVERAGE\x10\x00\x12\x07\n\x03\x41\x44\x44\x10\x01\x12\x0c\n\x08\x44\x45\x43REASE\x10\x02\x12\n\n\x06\x43\x41NCEL\x10\x03\x42\x34\n\x1a\x63om.htsc.mdc.hawkeye.modelB\x11MDSubscribeProtosH\x01\xa0\x01\x01\x62\x06proto3')
  ,
  dependencies=[SecuritySourceType__pb2.DESCRIPTOR,EMarketDataType__pb2.DESCRIPTOR,InsightErrorContext__pb2.DESCRIPTOR,])

_ESUBSCRIBEACTIONTYPE = _descriptor.EnumDescriptor(
  name='ESubscribeActionType',
  full_name='com.htsc.mdc.hawkeye.model.ESubscribeActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COVERAGE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ADD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DECREASE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CANCEL', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=1226,
  serialized_end=1297,
)
_sym_db.RegisterEnumDescriptor(_ESUBSCRIBEACTIONTYPE)

ESubscribeActionType = enum_type_wrapper.EnumTypeWrapper(_ESUBSCRIBEACTIONTYPE)
COVERAGE = 0
ADD = 1
DECREASE = 2
CANCEL = 3



_MDSUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='MDSubscribeRequest',
  full_name='com.htsc.mdc.hawkeye.model.MDSubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscribeActionType', full_name='com.htsc.mdc.hawkeye.model.MDSubscribeRequest.subscribeActionType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subscribeAll', full_name='com.htsc.mdc.hawkeye.model.MDSubscribeRequest.subscribeAll', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subscribeBySourceType', full_name='com.htsc.mdc.hawkeye.model.MDSubscribeRequest.subscribeBySourceType', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subscribeByID', full_name='com.htsc.mdc.hawkeye.model.MDSubscribeRequest.subscribeByID', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=437,
)


_SUBSCRIBEALL = _descriptor.Descriptor(
  name='SubscribeAll',
  full_name='com.htsc.mdc.hawkeye.model.SubscribeAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='marketDataTypes', full_name='com.htsc.mdc.hawkeye.model.SubscribeAll.marketDataTypes', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=523,
)


_SUBSCRIBEBYID = _descriptor.Descriptor(
  name='SubscribeByID',
  full_name='com.htsc.mdc.hawkeye.model.SubscribeByID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscribeByIDDetails', full_name='com.htsc.mdc.hawkeye.model.SubscribeByID.subscribeByIDDetails', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='globalMarketDataTypes', full_name='com.htsc.mdc.hawkeye.model.SubscribeByID.globalMarketDataTypes', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=696,
)


_SUBSCRIBEBYIDDETAIL = _descriptor.Descriptor(
  name='SubscribeByIDDetail',
  full_name='com.htsc.mdc.hawkeye.model.SubscribeByIDDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='htscSecurityID', full_name='com.htsc.mdc.hawkeye.model.SubscribeByIDDetail.htscSecurityID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marketDataTypes', full_name='com.htsc.mdc.hawkeye.model.SubscribeByIDDetail.marketDataTypes', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=698,
  serialized_end=813,
)


_SUBSCRIBEBYSOURCETYPE = _descriptor.Descriptor(
  name='SubscribeBySourceType',
  full_name='com.htsc.mdc.hawkeye.model.SubscribeBySourceType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subscribeBySourceTypeDetail', full_name='com.htsc.mdc.hawkeye.model.SubscribeBySourceType.subscribeBySourceTypeDetail', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=815,
  serialized_end=932,
)


_SUBSCRIBEBYSOURCETYPEDETAIL = _descriptor.Descriptor(
  name='SubscribeBySourceTypeDetail',
  full_name='com.htsc.mdc.hawkeye.model.SubscribeBySourceTypeDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='securitySourceTypes', full_name='com.htsc.mdc.hawkeye.model.SubscribeBySourceTypeDetail.securitySourceTypes', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='marketDataTypes', full_name='com.htsc.mdc.hawkeye.model.SubscribeBySourceTypeDetail.marketDataTypes', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=935,
  serialized_end=1111,
)


_MDSUBSCRIBERESPONSE = _descriptor.Descriptor(
  name='MDSubscribeResponse',
  full_name='com.htsc.mdc.hawkeye.model.MDSubscribeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='com.htsc.mdc.hawkeye.model.MDSubscribeResponse.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorContext', full_name='com.htsc.mdc.hawkeye.model.MDSubscribeResponse.errorContext', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1113,
  serialized_end=1224,
)

_MDSUBSCRIBEREQUEST.fields_by_name['subscribeActionType'].enum_type = _ESUBSCRIBEACTIONTYPE
_MDSUBSCRIBEREQUEST.fields_by_name['subscribeAll'].message_type = _SUBSCRIBEALL
_MDSUBSCRIBEREQUEST.fields_by_name['subscribeBySourceType'].message_type = _SUBSCRIBEBYSOURCETYPE
_MDSUBSCRIBEREQUEST.fields_by_name['subscribeByID'].message_type = _SUBSCRIBEBYID
_SUBSCRIBEALL.fields_by_name['marketDataTypes'].enum_type = EMarketDataType__pb2._EMARKETDATATYPE
_SUBSCRIBEBYID.fields_by_name['subscribeByIDDetails'].message_type = _SUBSCRIBEBYIDDETAIL
_SUBSCRIBEBYID.fields_by_name['globalMarketDataTypes'].enum_type = EMarketDataType__pb2._EMARKETDATATYPE
_SUBSCRIBEBYIDDETAIL.fields_by_name['marketDataTypes'].enum_type = EMarketDataType__pb2._EMARKETDATATYPE
_SUBSCRIBEBYSOURCETYPE.fields_by_name['subscribeBySourceTypeDetail'].message_type = _SUBSCRIBEBYSOURCETYPEDETAIL
_SUBSCRIBEBYSOURCETYPEDETAIL.fields_by_name['securitySourceTypes'].message_type = SecuritySourceType__pb2._SECURITYSOURCETYPE
_SUBSCRIBEBYSOURCETYPEDETAIL.fields_by_name['marketDataTypes'].enum_type = EMarketDataType__pb2._EMARKETDATATYPE
_MDSUBSCRIBERESPONSE.fields_by_name['errorContext'].message_type = InsightErrorContext__pb2._INSIGHTERRORCONTEXT
DESCRIPTOR.message_types_by_name['MDSubscribeRequest'] = _MDSUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name['SubscribeAll'] = _SUBSCRIBEALL
DESCRIPTOR.message_types_by_name['SubscribeByID'] = _SUBSCRIBEBYID
DESCRIPTOR.message_types_by_name['SubscribeByIDDetail'] = _SUBSCRIBEBYIDDETAIL
DESCRIPTOR.message_types_by_name['SubscribeBySourceType'] = _SUBSCRIBEBYSOURCETYPE
DESCRIPTOR.message_types_by_name['SubscribeBySourceTypeDetail'] = _SUBSCRIBEBYSOURCETYPEDETAIL
DESCRIPTOR.message_types_by_name['MDSubscribeResponse'] = _MDSUBSCRIBERESPONSE
DESCRIPTOR.enum_types_by_name['ESubscribeActionType'] = _ESUBSCRIBEACTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDSubscribeRequest = _reflection.GeneratedProtocolMessageType('MDSubscribeRequest', (_message.Message,), dict(
  DESCRIPTOR = _MDSUBSCRIBEREQUEST,
  __module__ = 'MDSubscribe_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.MDSubscribeRequest)
  ))
_sym_db.RegisterMessage(MDSubscribeRequest)

SubscribeAll = _reflection.GeneratedProtocolMessageType('SubscribeAll', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEALL,
  __module__ = 'MDSubscribe_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.SubscribeAll)
  ))
_sym_db.RegisterMessage(SubscribeAll)

SubscribeByID = _reflection.GeneratedProtocolMessageType('SubscribeByID', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEBYID,
  __module__ = 'MDSubscribe_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.SubscribeByID)
  ))
_sym_db.RegisterMessage(SubscribeByID)

SubscribeByIDDetail = _reflection.GeneratedProtocolMessageType('SubscribeByIDDetail', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEBYIDDETAIL,
  __module__ = 'MDSubscribe_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.SubscribeByIDDetail)
  ))
_sym_db.RegisterMessage(SubscribeByIDDetail)

SubscribeBySourceType = _reflection.GeneratedProtocolMessageType('SubscribeBySourceType', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEBYSOURCETYPE,
  __module__ = 'MDSubscribe_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.SubscribeBySourceType)
  ))
_sym_db.RegisterMessage(SubscribeBySourceType)

SubscribeBySourceTypeDetail = _reflection.GeneratedProtocolMessageType('SubscribeBySourceTypeDetail', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIBEBYSOURCETYPEDETAIL,
  __module__ = 'MDSubscribe_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.SubscribeBySourceTypeDetail)
  ))
_sym_db.RegisterMessage(SubscribeBySourceTypeDetail)

MDSubscribeResponse = _reflection.GeneratedProtocolMessageType('MDSubscribeResponse', (_message.Message,), dict(
  DESCRIPTOR = _MDSUBSCRIBERESPONSE,
  __module__ = 'MDSubscribe_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.hawkeye.model.MDSubscribeResponse)
  ))
_sym_db.RegisterMessage(MDSubscribeResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.htsc.mdc.hawkeye.modelB\021MDSubscribeProtosH\001\240\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
