# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDVwap.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EMDPeriodType_pb2 as EMDPeriodType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDVwap.proto',
  package='com.htsc.mdc.model',
  syntax='proto3',
  serialized_pb=_b('\n\x0cMDVwap.proto\x12\x12\x63om.htsc.mdc.model\x1a\x13\x45MDPeriodType.proto\"\xf6\x01\n\x06MDVwap\x12\x12\n\nMDRecordID\x18\x01 \x01(\t\x12\x35\n\nPeriodType\x18\x02 \x01(\x0e\x32!.com.htsc.mdc.model.EMDPeriodType\x12\x12\n\nSecurityID\x18\x03 \x01(\t\x12\x16\n\x0eHTSCSecurityID\x18\x04 \x01(\t\x12\x0e\n\x06MDDate\x18\x05 \x01(\t\x12\x0e\n\x06MDTime\x18\x06 \x01(\t\x12\x11\n\tStartDate\x18\x07 \x01(\t\x12\x11\n\tStartTime\x18\x08 \x01(\t\x12\x11\n\tTypicalPx\x18\t \x01(\x01\x12\x0e\n\x06Volume\x18\n \x01(\x01\x12\x0c\n\x04Vwap\x18\x0b \x01(\x01\x42\'\n\x12\x63om.htsc.mdc.modelB\x0cMDVwapProtosH\x01\xa0\x01\x01\x62\x06proto3')
  ,
  dependencies=[EMDPeriodType__pb2.DESCRIPTOR,])




_MDVWAP = _descriptor.Descriptor(
  name='MDVwap',
  full_name='com.htsc.mdc.model.MDVwap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MDRecordID', full_name='com.htsc.mdc.model.MDVwap.MDRecordID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PeriodType', full_name='com.htsc.mdc.model.MDVwap.PeriodType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SecurityID', full_name='com.htsc.mdc.model.MDVwap.SecurityID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HTSCSecurityID', full_name='com.htsc.mdc.model.MDVwap.HTSCSecurityID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDDate', full_name='com.htsc.mdc.model.MDVwap.MDDate', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDTime', full_name='com.htsc.mdc.model.MDVwap.MDTime', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartDate', full_name='com.htsc.mdc.model.MDVwap.StartDate', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartTime', full_name='com.htsc.mdc.model.MDVwap.StartTime', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TypicalPx', full_name='com.htsc.mdc.model.MDVwap.TypicalPx', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Volume', full_name='com.htsc.mdc.model.MDVwap.Volume', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Vwap', full_name='com.htsc.mdc.model.MDVwap.Vwap', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=304,
)

_MDVWAP.fields_by_name['PeriodType'].enum_type = EMDPeriodType__pb2._EMDPERIODTYPE
DESCRIPTOR.message_types_by_name['MDVwap'] = _MDVWAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDVwap = _reflection.GeneratedProtocolMessageType('MDVwap', (_message.Message,), dict(
  DESCRIPTOR = _MDVWAP,
  __module__ = 'MDVwap_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.model.MDVwap)
  ))
_sym_db.RegisterMessage(MDVwap)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022com.htsc.mdc.modelB\014MDVwapProtosH\001\240\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
