# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

# import hset_pb2 as hset__pb2
from .hset_pb2 import *

class HsetServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.hset = channel.unary_stream(
        '/com.htsc.xquant.protobuf.HsetService/hset',
        request_serializer=HsetRequest.SerializeToString,
        response_deserializer=HsetResponse.FromString,
        )


class HsetServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def hset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HsetServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'hset': grpc.unary_stream_rpc_method_handler(
          servicer.hset,
          request_deserializer=HsetRequest.FromString,
          response_serializer=HsetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.htsc.xquant.protobuf.HsetService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
