# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

# import stockFilter_pb2 as stockFilter__pb2
from .stockFilter_pb2 import *

class StockFilterServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.flush = channel.unary_stream(
        '/com.htsc.xquant.protobuf.StockFilterService/flush',
        request_serializer=StockDataRequest.SerializeToString,
        response_deserializer=StockDataResponse.FromString,
        )


class StockFilterServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def flush(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StockFilterServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'flush': grpc.unary_stream_rpc_method_handler(
          servicer.flush,
          request_deserializer=StockDataRequest.FromString,
          response_serializer=StockDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.htsc.xquant.protobuf.StockFilterService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
