# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tansday.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tansday.proto',
  package='com.htsc.xquant.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\rtansday.proto\x12\x18\x63om.htsc.xquant.protobuf\"\x86\x01\n\x11TradingDayRequest\x12\x12\n\nstart_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\x12\x11\n\tfrequency\x18\x03 \x01(\x05\x12\x10\n\x08\x64\x61y_type\x18\x04 \x01(\x05\x12\x11\n\tdate_type\x18\x05 \x01(\x05\x12\x13\n\x0bmarket_type\x18\x06 \x01(\x05\"F\n\x0eTradingDayData\x12\x0b\n\x03\x64\x61y\x18\x01 \x01(\t\x12\x12\n\nis_trading\x18\x02 \x01(\t\x12\x13\n\x0bmarket_type\x18\x03 \x01(\x05\"q\n\x12TradingDayResponse\x12\x12\n\nresultCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x36\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32(.com.htsc.xquant.protobuf.TradingDayData2~\n\x11TradingDayService\x12i\n\ntradingDay\x12+.com.htsc.xquant.protobuf.TradingDayRequest\x1a,.com.htsc.xquant.protobuf.TradingDayResponse\"\x00\x42?\n*com.htsc.xquant.factor.datacenter.protobufB\x0fTradingDayProtoP\x01\x62\x06proto3')
)




_TRADINGDAYREQUEST = _descriptor.Descriptor(
  name='TradingDayRequest',
  full_name='com.htsc.xquant.protobuf.TradingDayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_time', full_name='com.htsc.xquant.protobuf.TradingDayRequest.start_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='com.htsc.xquant.protobuf.TradingDayRequest.end_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='com.htsc.xquant.protobuf.TradingDayRequest.frequency', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day_type', full_name='com.htsc.xquant.protobuf.TradingDayRequest.day_type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_type', full_name='com.htsc.xquant.protobuf.TradingDayRequest.date_type', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='market_type', full_name='com.htsc.xquant.protobuf.TradingDayRequest.market_type', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=178,
)


_TRADINGDAYDATA = _descriptor.Descriptor(
  name='TradingDayData',
  full_name='com.htsc.xquant.protobuf.TradingDayData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='day', full_name='com.htsc.xquant.protobuf.TradingDayData.day', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_trading', full_name='com.htsc.xquant.protobuf.TradingDayData.is_trading', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='market_type', full_name='com.htsc.xquant.protobuf.TradingDayData.market_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=250,
)


_TRADINGDAYRESPONSE = _descriptor.Descriptor(
  name='TradingDayResponse',
  full_name='com.htsc.xquant.protobuf.TradingDayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='com.htsc.xquant.protobuf.TradingDayResponse.resultCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.htsc.xquant.protobuf.TradingDayResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='com.htsc.xquant.protobuf.TradingDayResponse.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=365,
)

_TRADINGDAYRESPONSE.fields_by_name['data'].message_type = _TRADINGDAYDATA
DESCRIPTOR.message_types_by_name['TradingDayRequest'] = _TRADINGDAYREQUEST
DESCRIPTOR.message_types_by_name['TradingDayData'] = _TRADINGDAYDATA
DESCRIPTOR.message_types_by_name['TradingDayResponse'] = _TRADINGDAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradingDayRequest = _reflection.GeneratedProtocolMessageType('TradingDayRequest', (_message.Message,), dict(
  DESCRIPTOR = _TRADINGDAYREQUEST,
  __module__ = 'tansday_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.TradingDayRequest)
  ))
_sym_db.RegisterMessage(TradingDayRequest)

TradingDayData = _reflection.GeneratedProtocolMessageType('TradingDayData', (_message.Message,), dict(
  DESCRIPTOR = _TRADINGDAYDATA,
  __module__ = 'tansday_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.TradingDayData)
  ))
_sym_db.RegisterMessage(TradingDayData)

TradingDayResponse = _reflection.GeneratedProtocolMessageType('TradingDayResponse', (_message.Message,), dict(
  DESCRIPTOR = _TRADINGDAYRESPONSE,
  __module__ = 'tansday_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.TradingDayResponse)
  ))
_sym_db.RegisterMessage(TradingDayResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*com.htsc.xquant.factor.datacenter.protobufB\017TradingDayProtoP\001'))

_TRADINGDAYSERVICE = _descriptor.ServiceDescriptor(
  name='TradingDayService',
  full_name='com.htsc.xquant.protobuf.TradingDayService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=367,
  serialized_end=493,
  methods=[
  _descriptor.MethodDescriptor(
    name='tradingDay',
    full_name='com.htsc.xquant.protobuf.TradingDayService.tradingDay',
    index=0,
    containing_service=None,
    input_type=_TRADINGDAYREQUEST,
    output_type=_TRADINGDAYRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRADINGDAYSERVICE)

DESCRIPTOR.services_by_name['TradingDayService'] = _TRADINGDAYSERVICE

# @@protoc_insertion_point(module_scope)
