month_mapper = {1: 'Jan',
                2: 'Feb',
                3: 'Mar',
                4: 'Apr',
                5: 'May',
                6: 'Jun',
                7: 'Jul',
                8: 'Aug',
                9: 'Sep',
                10: 'Oct',
                11: 'Nov',
                12: 'Dec'}

CITIC_I_mapper = {1: 'Petrochemical',
                  2: 'Coal',
                  3: 'Nonferrous Metals',
                  4: 'Electricity & Utilities',
                  5: 'Steel',
                  6: 'Basic Chemicals',
                  7: 'Construction',
                  8: 'Building Materials',
                  9: 'Light Industry',
                  10: 'Machinery',
                  11: 'Power Equipment',
                  12: 'National Defense',
                  13: 'Automobiles',
                  14: 'Retail Trade',
                  15: 'Catering & Travel',
                  16: 'Home Appliances',
                  17: 'Textiles & Garments',
                  18: 'Pharmaceuticals',
                  19: 'Food & Beverages',
                  20: 'Agriculture, Forestry, Animal Husbandry & Fishery',
                  21: 'Banks',
                  29: 'Non-banking Finance',
                  22: 'Real Estate',
                  23: 'Transportation (Combined)',
                  24: 'Electronic Components',
                  25: 'Communications',
                  26: 'Computers',
                  27: 'Media',
                  28: 'Comprehensive',
                  29: 'Securities II',
                  30: 'Insurance II',
                  31: 'Trust and Other'}

CITIC_I_abbr_mapper = {1: 'Petrochem',
                       2: 'Coal',
                       3: 'NonfMetals',
                       4: 'Elctr&Utls',
                       5: 'Steel',
                       6: 'BasicChem',
                       7: 'Construct',
                       8: 'BuildMat',
                       9: 'LightInd',
                       10: 'Machinery',
                       11: 'PowerEquip',
                       12: 'Defense',
                       13: 'Auto',
                       14: 'Retail',
                       15: 'Cater&Travel',
                       16: 'HomeApp',
                       17: 'Text&Garm',
                       18: 'Pharma',
                       19: 'Food&Bev',
                       20: 'AgrFstAniFsh',
                       21: 'Banks',
                       29: 'NonBankFin',
                       22: 'RealEstate',
                       23: 'Transport',
                       24: 'ElectComp',
                       25: 'Commn',
                       26: 'Computers',
                       27: 'Media',
                       28: 'Comp',
                       29: 'Secu II',
                       30: 'Insur II',
                       31: 'Trust&Otr'}

KNN_I_mapper = {1: 'Financial',
                2: 'TMT',
                3: 'Resources',
                4: 'Consumer',
                5: 'Misc'}

trade_cycle_mapper = {'DAILY': 1,
                      'WEEKLY': 5,
                      'BIWEEKLY': 10,
                      'MONTHLY': 20,
                      'QUARTERLY': 60}
