# _*_ coding:utf-8 _*_
import os
import json

encrypt_path = os.path.join('/'.join(os.path.abspath(__file__).split('/')[:-1]), "encrypted_database.json")

with open(encrypt_path, 'rb') as f:
    ENCRYPTED_HOSTS = json.load(f)

# 0 为测试环境 1为生产环境
switch = 1

Tel_shen = 17788398025
Tel_song = 18588266330
Tel_tao = 13770526625
Tel_cai = 18351858651
Tel_bie = 13355550671
Tel_li = 18100622199
Tel_huang = 18066116920
Tel_zhou = 18936880809
Tel_ding = 18845890982
Tel_Qin = 18168107133
Tel_Zhang = 18900662240
Tel_sjyy1 = 18216169518
Tel_sjyy2 = 18173990019
Tel_sjyy3 = 15707471660
Tel_sjyy4 = 18821652048
Tel_sjyy = 19936873976

if switch == 0:
    mysql_xquant_config = {"user": "xquant",
                           "passwd": ENCRYPTED_HOSTS['xquant']['test']['xquant']['ciphertext'],
                           "host": "168.63.1.130",
                           "db": "xquant",
                           "port": 3309
                           }

    mysql_xquant_data_config = {"user": "xquant_data",
                                "passwd": ENCRYPTED_HOSTS['xquant']['test']['xquant_data']['ciphertext'],
                                "host": "168.63.1.130",
                                "db": "xquant_data",
                                "port": 3309
                                }

    mysql_xquant_wind_config = {
        'host': '168.63.1.130',
        'user': 'xquant_wind',
        'passwd': ENCRYPTED_HOSTS['xquant']['test']['xquant_wind']['ciphertext'],
        'db': 'xquant_wind',
        'port': 3309,
        'charset': 'utf8'
    }

    mysql_xquant_gogoal_config = {
        'host': '168.63.1.130',
        'user': 'xquant_gogoal',
        'passwd': ENCRYPTED_HOSTS['xquant']['test']['xquant_gogoal']['ciphertext'],
        'db': 'xquant_gogoal',
        'port': 3309,
        'charset': 'utf8'
    }

    cloud_connstr = "center_admin/timegao@168.61.2.2:1521/servdb"

    # 短信平台对应的数据库连接信息
    sql_server_config = {"user": "test02",
                         "passwd": "Myjsy,Bjwqt_0",
                         "host": "168.60.17.117",
                         "db": "sms",
                         "port": "1433"
                         }
elif switch == 1:
    mysql_xquant_config = {
        'host': '168.6.68.72',
        'user': 'xquant',
        'passwd': ENCRYPTED_HOSTS['xquant']['prd']["xquant"]['ciphertext'],
        'db': 'xquant',
        'port': 3306,
        'charset': 'utf8'
    }

    mysql_xquant_data_config = {
        'host': '168.6.68.72',
        'user': 'xquant_data',
        'passwd': ENCRYPTED_HOSTS['xquant']['prd']["xquant_data"]['ciphertext'],
        'db': 'xquant_data',
        'port': 3306,
        'charset': 'utf8'
    }

    mysql_xquant_gogoal_config = {
        'host': '168.6.68.72',
        'user': 'xquant_gogoal',
        'passwd': ENCRYPTED_HOSTS['xquant']['prd']["xquant_gogoal"]['ciphertext'],
        'db': 'xquant_gogoal',
        'port': 3306,
        'charset': 'utf8'
    }

    mysql_xquant_wind_config = {
        'host': '168.6.68.72',
        'user': 'xquant_wind',
        'passwd': ENCRYPTED_HOSTS['xquant']['prd']["xquant_wind"]['ciphertext'],
        'db': 'xquant_wind',
        'port': 3306,
        'charset': 'utf8'
    }

    cloud_connstr = 'center_read/Htsc_Htzx@qdb04-000285.cbegq5uaeort.rds.cn-north-1.amazonaws.com.cn:1521/QDB04'

    # 短信平台对应的数据库连接信息
    sql_server_config = {"user": "KF_EMP",
                         "passwd": "Emp@2017",
                         "host": "168.9.8.81",
                         "db": "sms",
                         "port": "1433"
                         }
else:
    raise Exception("switch:0 为测试环境配置 1为生产环境配置")

factor_msg = {
    'H5': {'AShareBalanceSheet': 'trade_dt_qf', 'AShareCashFlow': 'trade_dt_qf', 'AShareIncome': 'trade_dt_qf',
           'AShareFinancialIndicator': 'trade_dt_qf', 'AShareIssuingDatePredict': 'trade_dt_qf',
           'AShareEODDerivativeIndicator': 'trade_dt', 'FCD_CHINA_STOCK_DAILY_SUNTIME': 'trade_dt',
           'con_forecast_schedule': 'trade_dt', 'stock_order3': 'trade_dt', 'stock_report_number': 'trade_dt',
           'stock_order2': 'trade_dt', 'stock_report_adjustment2': 'trade_dt', 'stock_concern_level': 'trade_dt',
           'con_stock_deviation3': 'trade_dt', 'cmb_report_adjust': 'trade_dt', 'con_forecast_c2_stk': 'trade_dt',
           'con_forecast_c3_stk': 'trade_dt', 'FDD_CHINA_STOCK_QUARTERLY_WIND_apturn': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_arturn': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_assetstoequity': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_assetsturn1': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_cashflow_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_cashtostdebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_catoassets': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_caturn': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_current': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_currentdebttodebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_currentdebttoequity': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_debttoassets': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ebitdatosales': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ebittoassets2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ebttoor_ttm': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_eps_basic': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_faturn': 'trade_dt_qf', 'FDD_CHINA_STOCK_QUARTERLY_WIND_fcfe': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_fcff': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_fcftocf': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_gc_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_gctogr_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_gr_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_grossmargin_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_grossprofitmargin': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_grossprofitmargin_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_intdebttototalcap': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_interestexpense_ttm': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_investincometoebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_invturn': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_longcapitaltoinvestment': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_longdebttodebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_longdebttolongcaptial': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ncatoequity': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_netprofitmargin_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_netprofittoassets': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_netprofittoor_ttm': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_nonoperateprofittoebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ocftoassets': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ocftocf': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ocftodebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ocftodividend': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ocftointerest': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ocftoop': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ocftoor_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_ocftosales': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_operatecaptialturn': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_operatecashflow_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_operateexpensetogr': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_operateincometoebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_operateincometoebt_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_optoebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_optogr': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_optogr_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_profit_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_profittogr': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_profittogr_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_grossmargin': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_grossprofitmargin': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_netprofitmargin': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_ocftoor': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_ocftosales': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_operateincome': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_operateincometoebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_profittogr': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_roa': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_roe': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_yoycf': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_yoyeps': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_yoygr': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_yoyocf': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_yoyop': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_yoyprofit': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_qfa_yoysales': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_quick': 'trade_dt_qf', 'FDD_CHINA_STOCK_QUARTERLY_WIND_roa': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_roa2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_roa2_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_roe_basic': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_roe_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_roic': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_roic_ttm2': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_stm_issuingdate': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_tot_assets': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_tot_equity': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_tot_liab': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_tot_non_cur_liab': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoy_assets': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoy_cash': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoy_equity': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoy_fixedassets': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoy_tr': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoydebt': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoyeps_basic': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoynetprofit': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoyocf': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoyocfps': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoyop': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoyprofit': 'trade_dt_qf',
           'FDD_CHINA_STOCK_QUARTERLY_WIND_yoyroe': 'trade_dt_qf'},
    'gaya': {'pre_close': 'trade_dt', 'open': 'trade_dt', 'high': 'trade_dt', 'low': 'trade_dt',
             'close': 'trade_dt', 'vwap': 'trade_dt', 'chg': 'trade_dt', 'pct_chg': 'trade_dt',
             'turn': 'trade_dt', 'free_turn': 'trade_dt', 'volume': 'trade_dt', 'amt': 'trade_dt',
             'dealnum': 'trade_dt', 'swing': 'trade_dt', 're_ipo_chg': 'trade_dt',
             'rel_ipo_pct_chg': 'trade_dt', 'trade_status': 'trade_dt', 'susp_reason': 'trade_dt',
             'lastradeday_s': 'trade_dt', 'last_trade_day': 'trade_dt', 'adjfactor': 'trade_dt',
             'maxupordown': 'trade_dt', 'total_shares': 'trade_dt', 'free_float_shares': 'trade_dt',
             'float_a_shares': 'trade_dt', 'share_totala': 'trade_dt', 'pre_close_badj': 'trade_dt',
             'open_badj': 'trade_dt', 'high_badj': 'trade_dt', 'low_badj': 'trade_dt',
             'close_badj': 'trade_dt', 're_ipo_chg_badj': 'trade_dt', 'rel_ipo_pct_chg_badj': 'trade_dt',
             'ev': 'trade_dt', 'mkt_cap_ard': 'trade_dt', 'a_mkt_cap': 'trade_dt', 'pe_ttm': 'trade_dt',
             'pe_lyr': 'trade_dt', 's_val_pb_new': 'trade_dt', 's_price_div_dps': 'trade_dt',
             'ps_ttm': 'trade_dt', 'ps_lyr': 'trade_dt', 'pcf_ocf_ttm': 'trade_dt', 'pcf_ncf_ttm': 'trade_dt',
             'pcf_ocflyr': 'trade_dt', 'pcf_ncflyr': 'trade_dt', 'net_assets_today': 'trade_dt',
             's_pq_high_52w_': 'trade_dt', 's_pq_low_52w_': 'trade_dt', 's_pq_adjhigh_52w': 'trade_dt',
             's_pq_adjlow_52w': 'trade_dt', 'net_profit_parent_comp_ttm': 'trade_dt',
             'net_profit_parent_comp_lyr': 'trade_dt', 'net_cash_flows_oper_act_ttm': 'trade_dt',
             'net_cash_flows_oper_act_lyr': 'trade_dt', 'oper_rev_ttm': 'trade_dt',
             'oper_rev_lyr': 'trade_dt', 'net_incr_cash_cash_equ_ttm': 'trade_dt',
             'net_incr_cash_cash_equ_lyr': 'trade_dt', 'up_down_limit_status': 'trade_dt',
             'lowest_highest_status': 'trade_dt', 'dividendyield': 'report_dt', 'dyr_12': 'trade_dt',
             'ev1': 'trade_dt', 'ev2': 'trade_dt', 'val_evtoebitda2': 'report_dt', 'profit_ttm': 'report_dt',
             'grossmargin_ttm': 'report_dt', 'or_ttm': 'report_dt', 'annualyeild_100w': 'trade_Friday',
             'annualyeild_24m': 'trade_month_end', 'annualyeild_60m': 'trade_month_end',
             'annualstdevr_100w': 'trade_Friday', 'annualstdevr_24m': 'trade_month_end',
             'annualstdevr_60m': 'trade_month_end', 'beta_100w': 'trade_dt', 'beta_24m': 'trade_dt',
             'beta_60m': 'trade_dt', 'eps_basic': 'report_dt', 'eps_diluted': 'report_dt',
             'eps_diluted2': 'report_dt', 'bps': 'report_dt', 'bps_adjust': 'report_dt',
             'bps_new': 'report_dt', 'ocfps': 'report_dt', 'ocfps_ttm': 'report_dt', 'grps': 'report_dt',
             'orps': 'report_dt', 'orps_ttm': 'report_dt', 'surpluscapitalps': 'report_dt',
             'surplusreserveps': 'report_dt', 'undistributedps': 'report_dt', 'retainedps': 'report_dt',
             'cfps': 'report_dt', 'cfps_ttm': 'report_dt', 'ebitps': 'report_dt', 'fcffps': 'report_dt',
             'fcfeps': 'report_dt', 'ebitdaps': 'report_dt', 'roe_diluted': 'report_dt', 'roa2': 'report_dt',
             'roa': 'report_dt', 'roic': 'report_dt', 'roic_ttm': 'report_dt', 'roe_yearly': 'report_dt',
             'roa2_yearly': 'report_dt', 'roa_yearly': 'report_dt', 'netprofitmargin': 'report_dt',
             'grossprofitmargin': 'report_dt', 'cogstosales': 'report_dt', 'expensetosales': 'report_dt',
             'nptocostexpense': 'report_dt', 'optoebt': 'report_dt', 'profittogr': 'report_dt',
             'optogr': 'report_dt', 'ebittogr': 'report_dt', 'gctogr': 'report_dt',
             'operateexpensetogr': 'report_dt', 'adminexpensetogr': 'report_dt',
             'finaexpensetogr': 'report_dt', 'impairtogr': 'report_dt', 'roe_ttm': 'report_dt',
             'roe2_ttm': 'report_dt', 'roa_ttm': 'report_dt', 'netprofitmargin_ttm': 'report_dt',
             'grossprofitmargin_ttm': 'report_dt', 'expensetosales_ttm': 'report_dt',
             'profittogr_ttm': 'report_dt', 'optogr_ttm': 'report_dt', 'gctogr_ttm': 'report_dt',
             'operateexpensetogr_ttm': 'report_dt', 'adminexpensetogr_ttm': 'report_dt',
             'finaexpensetogr_ttm': 'report_dt', 'impairtogr_ttm': 'report_dt', 'impairtoOP': 'report_dt',
             'ebitdatosales': 'report_dt', 'grossmargin': 'report_dt', 's_qfa_yoyop': 'report_dt',
             's_qfa_yoyprofit': 'report_dt', 's_qfa_cgrsales': 'report_dt', 'waa_roe': 'report_dt',
             'operateincometoebt': 'report_dt', 'investincometoebt': 'report_dt',
             'nonoperateprofittoebt': 'report_dt', 'taxtoebt': 'report_dt',
             'deductedprofittoprofit': 'report_dt', 'operateincometoebt_ttm': 'report_dt',
             'investincometoebt_ttm': 'report_dt', 'nonoperateprofittoebt_ttm': 'report_dt',
             'extraordinary': 'report_dt', 'deductedprofit': 'report_dt', 'salescashintoor': 'report_dt',
             'ocftoor': 'report_dt', 'ocftooperateincome': 'report_dt', 'capitalizedtoda': 'report_dt',
             'salescashintoor_ttm': 'report_dt', 'ocftoor_ttm': 'report_dt',
             'ocftooperateincome_ttm': 'report_dt', 'ocftocf': 'report_dt', 'icftocf': 'report_dt',
             'fcftocf': 'report_dt', 'ocftosales': 'report_dt', 'ocftoinveststockdividend': 'report_dt',
             'ocftoop': 'report_dt', 'ocftoassets': 'report_dt', 'ocftodividend': 'report_dt',
             'net_cash_flows_oper': 'report_dt', 'debttoassets': 'report_dt',
             'deducteddebttoassets': 'report_dt', 'longdebttolongcaptial': 'report_dt',
             'longcapitaltoinvestment': 'report_dt', 'assetstoequity': 'report_dt', 'catoassets': 'report_dt',
             'ncatoassets': 'report_dt', 'tangibleassetstoassets': 'report_dt',
             'longdebttoequity': 'report_dt', 'currentdebttoequity': 'report_dt',
             'equitytototalcapital': 'report_dt', 'intdebttototalcap': 'report_dt',
             'currentdebttodebt': 'report_dt', 'longdebtodebt': 'report_dt', 'ncatoequity': 'report_dt',
             'current': 'report_dt', 'quick': 'report_dt', 'cashratio': 'report_dt',
             'cashtocurrentdebt': 'report_dt', 'ocftoquickdebt': 'report_dt', 'ocftointerest': 'report_dt',
             'debttoequity': 'report_dt', 'equitytodebt': 'report_dt', 'equitytointerestdebt': 'report_dt',
             'tangassettointdebt': 'report_dt', 'tangibleassettodebt': 'report_dt',
             'tangibleassettonetdebt': 'report_dt', 'ebitdatodebt': 'report_dt', 'ocftodebt': 'report_dt',
             'ocftointerestdebt': 'report_dt', 'ocftoshortdebt': 'report_dt', 'ocftonetdebt': 'report_dt',
             'ocftolongdebt': 'report_dt', 'ocficftocurrentdebt': 'report_dt', 'ocficftodebt': 'report_dt',
             'ebittointerest': 'report_dt', 'longdebttoworkingcapital': 'report_dt',
             'longdebttodebt': 'report_dt', 'debttotangibleequity': 'report_dt', 'netdebttoev': 'report_dt',
             'interestdebttoev': 'report_dt', 'ebitdatointerestdebt': 'report_dt',
             'ebitdatointerest': 'report_dt', 'tltoebitda': 'report_dt', 'cashtostdebt': 'report_dt',
             'turndays': 'report_dt', 'invturndays': 'report_dt', 'arturndays': 'report_dt',
             'apturndays': 'report_dt', 'netturndays': 'report_dt', 'invturn': 'report_dt',
             'arturn': 'report_dt', 'caturn': 'report_dt', 'operatecapitalturn': 'report_dt',
             'faturn': 'report_dt', 'non_currentassetsturn': 'report_dt', 'assetsturn': 'report_dt',
             'apturn': 'report_dt', 'yoyeps_basic': 'report_dt', 'yoyeps_diluted': 'report_dt',
             'yoyocfps': 'report_dt', 'yoy_tr': 'report_dt', 'yoy_or': 'report_dt', 'yoyop': 'report_dt',
             'yoyebt': 'report_dt', 'yoyprofit': 'report_dt', 'yoynetprofit': 'report_dt',
             'yoynetprofit_deducted': 'report_dt', 'yoyocf': 'report_dt', 'yoyroe': 'report_dt',
             'yoy_equity': 'report_dt', 'yoydebt': 'report_dt', 'yoy_assets': 'report_dt',
             'yoycf': 'report_dt', 'maintenance': 'report_dt', 'yoy_cash': 'report_dt',
             'yoy_fixedassets': 'report_dt', 'yoybps': 'report_dt', 'yoyassets': 'report_dt',
             'yoyequity': 'report_dt', 'stm_issuingdate': 'report_dt', 'stm_predict_issuingdate': 'report_dt',
             's_div_preanndt': 'report_dt', 'monetary_cap': 'report_dt', 'tradable_fin_assets': 'report_dt',
             'notes_rcv': 'report_dt', 'acct_rcv': 'report_dt', 'oth_rcv': 'report_dt', 'prepay': 'report_dt',
             'dvd_rcv': 'report_dt', 'int_rcv': 'report_dt', 'inventories': 'report_dt',
             'consumptive_bio_assets': 'report_dt', 'deferred_exp': 'report_dt',
             'non_cur_assets_due_within_1y': 'report_dt', 'settle_rsrv': 'report_dt',
             'loans_to_oth_banks': 'report_dt', 'prem_rcv': 'report_dt', 'rcv_from_reinsurer': 'report_dt',
             'rcv_from_ceded_insur_cont_rsrv': 'report_dt', 'red_monetary_cap_for_sale': 'report_dt',
             'oth_cur_assets': 'report_dt', 'tot_cur_assets': 'report_dt',
             'fin_assets_avail_for_sale': 'report_dt', 'held_to_mty_invest': 'report_dt',
             'long_term_eqy_invest': 'report_dt', 'invest_real_estate': 'report_dt',
             'time_deposits': 'report_dt', 'oth_assets': 'report_dt', 'long_term_rec': 'report_dt',
             'fix_assets': 'report_dt', 'const_in_prog': 'report_dt', 'proj_matl': 'report_dt',
             'fix_assets_disp': 'report_dt', 'productive_bio_assets': 'report_dt',
             'oil_and_natural_gas_assets': 'report_dt', 'intang_assets': 'report_dt',
             'r_and_d_costs': 'report_dt', 'goodwill': 'report_dt', 'long_term_deferred_exp': 'report_dt',
             'deferred_tax_assets': 'report_dt', 'loans_and_adv_granted': 'report_dt',
             'oth_non_cur_assets': 'report_dt', 'tot_non_cur_assets': 'report_dt',
             'cash_deposits_central_bank': 'report_dt', 'asset_dep_oth_banks_fin_inst': 'report_dt',
             'precious_metals': 'report_dt', 'derivative_fin_assets': 'report_dt',
             'agency_bus_assets': 'report_dt', 'subr_rec': 'report_dt',
             'rcv_ceded_unearned_prem_rsrv': 'report_dt', 'rcv_ceded_claim_rsrv': 'report_dt',
             'rcv_ceded_life_insur_rsrv': 'report_dt', 'rcv_ceded_lt_health_insur_rsrv': 'report_dt',
             'mrgn_paid': 'report_dt', 'insured_pledge_loan': 'report_dt', 'cap_mrgn_paid': 'report_dt',
             'independent_acct_assets': 'report_dt', 'clients_cap_deposit': 'report_dt',
             'clients_rsrv_settle': 'report_dt', 'incl_seat_fees_exchange': 'report_dt',
             'rcv_invest': 'report_dt', 'tot_assets': 'report_dt', 'st_borrow': 'report_dt',
             'borrow_central_bank': 'report_dt', 'deposit_received_ib_deposits': 'report_dt',
             'loans_oth_banks': 'report_dt', 'tradable_fin_liab': 'report_dt', 'notes_payable': 'report_dt',
             'acct_payable': 'report_dt', 'adv_from_cust': 'report_dt',
             'fund_sales_fin_assets_rp': 'report_dt', 'handling_charges_comm_payable': 'report_dt',
             'empl_ben_payable': 'report_dt', 'taxes_surcharges_payable': 'report_dt',
             'int_payable': 'report_dt', 'dvd_payable': 'report_dt', 'oth_payable': 'report_dt',
             'acc_exp': 'report_dt', 'deferred_inc': 'report_dt', 'st_bonds_payable': 'report_dt',
             'payable_to_reinsurer': 'report_dt', 'rsrv_insur_cont': 'report_dt',
             'acting_trading_sec': 'report_dt', 'acting_uw_sec': 'report_dt',
             'non_cur_liab_due_within_1y': 'report_dt', 'oth_cur_liab': 'report_dt',
             'tot_cur_liab': 'report_dt', 'lt_borrow': 'report_dt', 'bonds_payable': 'report_dt',
             'lt_payable': 'report_dt', 'specific_item_payable': 'report_dt', 'provisions': 'report_dt',
             'deferred_tax_liab': 'report_dt', 'deferred_inc_non_cur_liab': 'report_dt',
             'oth_non_cur_liab': 'report_dt', 'tot_non_cur_liab': 'report_dt',
             'liab_dep_oth_banks_fin_inst': 'report_dt', 'derivative_fin_liab': 'report_dt',
             'cust_bank_dep': 'report_dt', 'agency_bus_liab': 'report_dt', 'oth_liab': 'report_dt',
             'prem_received_adv': 'report_dt', 'deposit_received': 'report_dt',
             'insured_deposit_invest': 'report_dt', 'unearned_prem_rsrv': 'report_dt',
             'out_loss_rsrv': 'report_dt', 'life_insur_rsrv': 'report_dt', 'lt_health_insur_v': 'report_dt',
             'independent_acct_liab': 'report_dt', 'incl_pledge_loan': 'report_dt',
             'claims_payable': 'report_dt', 'dvd_payable_insured': 'report_dt', 'tot_liab': 'report_dt',
             'cap_stk': 'report_dt', 'cap_rsrv': 'report_dt', 'special_rsrv': 'report_dt',
             'surplus_rsrv': 'report_dt', 'undistributed_profit_b': 'report_dt', 'less_tsy_stk': 'report_dt',
             'prov_nom_risks': 'report_dt', 'cnvd_diff_foreign_curr_stat': 'report_dt',
             'unconfirmed_invest_loss_c': 'report_dt', 'minority_int': 'report_dt',
             'tot_shrhldr_eqy_excl_min_int': 'report_dt', 'tot_shrhldr_eqy_incl_min_int': 'report_dt',
             'tot_liab_shrhldr_eqy': 'report_dt', 'actual_ann_dt_c': 'report_dt',
             'spe_cur_assets_diff': 'report_dt', 'tot_cur_assets_diff': 'report_dt',
             'spe_non_cur_assets_diff': 'report_dt', 'tot_non_cur_assets_diff': 'report_dt',
             'spe_bal_assets_diff': 'report_dt', 'tot_bal_assets_diff': 'report_dt',
             'spe_cur_liab_diff': 'report_dt', 'tot_cur_liab_diff': 'report_dt',
             'spe_non_cur_liab_diff': 'report_dt', 'tot_non_cur_liab_diff': 'report_dt',
             'spe_bal_liab_diff': 'report_dt', 'tot_bal_liab_diff': 'report_dt',
             'spe_bal_shrhldr_eqy_diff': 'report_dt', 'tot_bal_shrhldr_eqy_diff': 'report_dt',
             'spe_bal_liab_eqy_diff': 'report_dt', 'tot_bal_liab_eqy_diff': 'report_dt',
             'lt_payroll_payable': 'report_dt', 'other_comp_income': 'report_dt',
             'other_equity_tools': 'report_dt', 'other_equity_tools_p_shr': 'report_dt',
             'lending_funds': 'report_dt', 'accounts_receivable': 'report_dt',
             'st_financing_payable': 'report_dt', 'payables': 'report_dt', 'tot_shr': 'report_dt',
             'hfs_assets': 'report_dt', 'tot_oper_rev': 'report_dt', 'oper_rev': 'report_dt',
             'int_inc': 'report_dt', 'net_int_inc': 'report_dt', 'insur_prem_unearned': 'report_dt',
             'handling_chrg_comm_inc': 'report_dt', 'net_handling_chrg_comm_inc': 'report_dt',
             'net_inc_other_ops': 'report_dt', 'plus_net_inc_other_bus': 'report_dt', 'prem_inc': 'report_dt',
             'less_ceded_out_prem': 'report_dt', 'chg_unearned_prem_res': 'report_dt',
             'incl_reinsurance_prem_inc': 'report_dt', 'net_inc_sec_trading_brok_bus': 'report_dt',
             'net_inc_sec_uw_bus': 'report_dt', 'net_inc_ec_asset_mgmt_bus': 'report_dt',
             'other_bus_inc': 'report_dt', 'plus_net_gain_chg_fv': 'report_dt',
             'plus_net_invest_inc': 'report_dt', 'incl_inc_invest_assoc_jv_entp': 'report_dt',
             'plus_net_gain_fx_trans': 'report_dt', 'tot_oper_cost': 'report_dt',
             'less_oper_cost': 'report_dt', 'less_int_exp': 'report_dt',
             'less_handling_chrg_comm_exp': 'report_dt', 'less_taxes_surcharges_ops': 'report_dt',
             'less_selling_dist_exp': 'report_dt', 'less_gerl_admin_exp': 'report_dt',
             'less_fin_exp': 'report_dt', 'less_impair_loss_assets': 'report_dt', 'prepay_surr': 'report_dt',
             'tot_claim_exp': 'report_dt', 'chg_insur_cont_rsrv': 'report_dt', 'dvd_exp_insured': 'report_dt',
             'reinsurance_exp': 'report_dt', 'oper_exp': 'report_dt',
             'less_claim_recb_reinsurer': 'report_dt', 'less_ins_rsrv_recb_reinsurer': 'report_dt',
             'less_exp_recb_reinsurer': 'report_dt', 'other_bus_cost': 'report_dt',
             'oper_profit': 'report_dt', 'plus_non_oper_rev': 'report_dt', 'less_non_oper_exp': 'report_dt',
             'il_net_loss_disp_noncur_asset': 'report_dt', 'tot_profit': 'report_dt', 'inc_tax': 'report_dt',
             'unconfirmed_invest_loss_b': 'report_dt', 'net_profit_incl_min_int_inc': 'report_dt',
             'net_profit_excl_min_int_inc': 'report_dt', 'minority_int_inc': 'report_dt',
             'other_compreh_inc': 'report_dt', 'tot_compreh_inc': 'report_dt',
             'tot_compreh_inc_parent_comp': 'report_dt', 'tot_compreh_inc_min_shrhldr': 'report_dt',
             'ebit': 'report_dt', 'ebitda': 'report_dt', 'net_profit_after_ded_nr_lp': 'report_dt',
             'net_profit_under_intl_acc_sta': 'report_dt', 's_fa_eps_basic': 'report_dt',
             's_fa_eps_diluted': 'report_dt', 'actual_ann_dt_b': 'report_dt',
             'insurance_expense': 'report_dt', 'spe_bal_oper_profit': 'report_dt',
             'tot_bal_oper_profit': 'report_dt', 'spe_bal_tot_profit': 'report_dt',
             'tot_bal_tot_profit': 'report_dt', 'spe_bal_net_profit': 'report_dt',
             'tot_bal_net_profit': 'report_dt', 'undistributed_profit_p': 'report_dt',
             'adjlossgain_prevyear': 'report_dt', 'transfer_from_surplusreserve': 'report_dt',
             'transfer_from_housingimprest': 'report_dt', 'transfer_from_others': 'report_dt',
             'distributable_profit': 'report_dt', 'withdr_legalsurplus': 'report_dt',
             'withdr_legalpubwelfunds': 'report_dt', 'workers_welfare': 'report_dt',
             'withdr_buzexpwelfare': 'report_dt', 'withdr_reservefund': 'report_dt',
             'distributable_profit_shrhder': 'report_dt', 'prfshare_dvd_payable': 'report_dt',
             'withdr_othersurpreserve': 'report_dt', 'comshare_dvd_payable': 'report_dt',
             'capitalized_comstock_div': 'report_dt', 'cash_recp_sg_and_rs': 'report_dt',
             'recp_tax_rends': 'report_dt', 'net_incr_dep_cob': 'report_dt',
             'net_incr_loans_central_bank': 'report_dt', 'net_incr_fund_borr_ofi': 'report_dt',
             'cash_recp_prem_orig_inco': 'report_dt', 'net_incr_insured_dep': 'report_dt',
             'net_cash_received_reinsu_bus': 'report_dt', 'net_incr_disp_tfa': 'report_dt',
             'net_incr_int_handling_chrg': 'report_dt', 'net_incr_disp_faas': 'report_dt',
             'net_incr_loans_other_bank': 'report_dt', 'net_incr_repurch_bus_fund': 'report_dt',
             'other_cash_recp_ral_oper_act': 'report_dt', 'stot_cash_inflows_oper_act': 'report_dt',
             'cash_pay_goods_purch_serv_rec': 'report_dt', 'cash_pay_beh_empl': 'report_dt',
             'pay_all_typ_tax': 'report_dt', 'net_incr_clients_loan_adv': 'report_dt',
             'net_incr_dep_cbob': 'report_dt', 'cash_pay_claims_orig_inco': 'report_dt',
             'handling_chrg_paid': 'report_dt', 'comm_insur_plcy_paid': 'report_dt',
             'other_cash_pay_ral_oper_act': 'report_dt', 'stot_cash_outflows_oper_act': 'report_dt',
             'net_cash_flows_oper_act': 'report_dt', 'cash_recp_disp_withdrwl_invest': 'report_dt',
             'cash_recp_return_invest': 'report_dt', 'net_cash_recp_disp_fiolta': 'report_dt',
             'net_cash_recp_disp_sobu': 'report_dt', 'other_cash_recp_ral_inv_act': 'report_dt',
             'stot_cash_inflows_inv_act': 'report_dt', 'cash_pay_acq_const_fiolta': 'report_dt',
             'cash_paid_invest': 'report_dt', 'net_cash_pay_aquis_sobu': 'report_dt',
             'other_cash_pay_ral_inv_act': 'report_dt', 'net_incr_pledge_loan': 'report_dt',
             'stot_cash_outflows_inv_act': 'report_dt', 'net_cash_flows_inv_act': 'report_dt',
             'cash_recp_cap_contrib': 'report_dt', 'incl_cash_rec_saims': 'report_dt',
             'cash_recp_borrow': 'report_dt', 'proc_issue_bonds': 'report_dt',
             'other_cash_recp_ral_fnc_act': 'report_dt', 'stot_cash_inflows_fnc_act': 'report_dt',
             'cash_prepay_amt_borr': 'report_dt', 'cash_pay_dist_dpcp_int_exp': 'report_dt',
             'incl_dvd_profit_paid_sc_ms': 'report_dt', 'other_cash_pay_ral_fnc_act': 'report_dt',
             'stot_cash_outflows_fnc_act': 'report_dt', 'net_cash_flows_fnc_act': 'report_dt',
             'eff_fx_flu_cash': 'report_dt', 'net_incr_cash_cash_equ': 'report_dt',
             'cash_cash_equ_beg_period': 'report_dt', 'cash_cash_equ_end_period': 'report_dt',
             'net_profit': 'report_dt', 'unconfirmed_invest_loss_p': 'report_dt',
             'plus_prov_depr_assets': 'report_dt', 'depr_fa_coga_dpba': 'report_dt',
             'amort_intang_assets': 'report_dt', 'amort_lt_deferred_exp': 'report_dt',
             'decr_deferred_exp': 'report_dt', 'incr_acc_exp': 'report_dt', 'loss_disp_fiolta': 'report_dt',
             'loss_scr_fa': 'report_dt', 'loss_fv_chg': 'report_dt', 'fin_exp': 'report_dt',
             'invest_loss': 'report_dt', 'decr_deferred_inc_tax_assets': 'report_dt',
             'incr_deferred_inc_tax_liab': 'report_dt', 'decr_inventories': 'report_dt',
             'decr_oper_payable': 'report_dt', 'incr_oper_payable': 'report_dt', 'others': 'report_dt',
             'im_net_cash_flows_oper_act': 'report_dt', 'conv_debt_into_cap': 'report_dt',
             'conv_corp_bonds_due_within_1y': 'report_dt', 'fa_fnc_leases': 'report_dt',
             'end_bal_cash': 'report_dt', 'less_beg_bal_cash': 'report_dt',
             'plus_end_bal_cash_equ': 'report_dt', 'less_beg_bal_cash_equ': 'report_dt',
             'im_net_incr_cash_cash_equ': 'report_dt', 'free_cash_flow': 'report_dt',
             'actual_ann_dt_p': 'report_dt', 'spe_bal_cash_inflows_oper': 'report_dt',
             'tot_bal_cash_inflows_oper': 'report_dt', 'spe_bal_cash_outflows_oper': 'report_dt',
             'tot_bal_cash_outflows_oper': 'report_dt', 'tot_bal_netcash_outflows_oper': 'report_dt',
             'spe_bal_cash_inflows_inv': 'report_dt', 'tot_bal_cash_inflows_inv': 'report_dt',
             'spe_bal_cash_outflows_inv': 'report_dt', 'tot_bal_cash_outflows_inv': 'report_dt',
             'tot_bal_netcash_outflows_inv': 'report_dt', 'spe_bal_cash_inflows_fnc': 'report_dt',
             'tot_bal_cash_inflows_fnc': 'report_dt', 'spe_bal_cash_outflows_fnc': 'report_dt',
             'tot_bal_cash_outflows_fnc': 'report_dt', 'tot_bal_netcash_outflows_fnc': 'report_dt',
             'spe_bal_netcash_inc': 'report_dt', 'tot_bal_netcash_inc': 'report_dt',
             'spe_bal_netcash_equ_undir': 'report_dt', 'tot_bal_netcash_equ_undir': 'report_dt',
             'spe_bal_netcash_inc_undir': 'report_dt', 'tot_bal_netcash_inc_undir': 'report_dt',
             'per_div_trans': 'report_dt', 'per_cashpaidbeforetax': 'report_dt',
             'per_cashpaidaftertax': 'report_dt', 'div_aualaccmdivpershare': 'report_dt',
             'div_aualaccmdiv': 'report_dt', 'div_cashpaidaftertax': 'report_dt',
             'div_cashpaidbeforetax': 'report_dt', 'ex_dt': 'report_dt', 'dvd_payout_dt': 'report_dt',
             'listing_dt_of_dvd_shr': 'report_dt', 's_div_smtgdate': 'report_dt', 'dvd_ann_dt': 'report_dt',
             's_div_progress': 'report_dt', 'per_cashpaidbeforetax_Declared': 'report_dt',
             'per_cashpaidaftertax_Declared': 'report_dt', 'short_name': 'trade_dt',
             'listing_date': 'trade_dt', 'listing_place': 'trade_dt', 'listing_board': 'trade_dt',
             'currency': 'trade_dt', 'delisting_date': 'trade_dt', 'con_sector': 'trade_dt',
             'key_indices_con': 'trade_dt', 'shhk_stk_conn': 'trade_dt', 'stpt': 'trade_dt', 'bond_open': 'trade_dt',
             'bond_high': 'trade_dt', 'bond_low': 'trade_dt', 'bond_close': 'trade_dt', 'bond_volume': 'trade_dt',
             'bond_amount': 'trade_dt', 'bond_trade_status': 'trade_dt', 'bond_pre_close': 'trade_dt',
             'bond_accrueddays': 'trade_dt', 'bond_accruedinterest': 'trade_dt', 'bond_ptm': 'trade_dt',
             'bond_curyield': 'trade_dt', 'bond_ytm': 'trade_dt', 'bond_strbvalue': 'trade_dt',
             'bond_strbpremium': 'trade_dt', 'bond_strbpremiumratio': 'trade_dt', 'bond_convprice': 'trade_dt',
             'bond_convratio': 'trade_dt', 'bond_convvalue': 'trade_dt', 'bond_convpremium': 'trade_dt',
             'bond_convpremiumratio': 'trade_dt', 'mdc_pre_close': 'trade_dt', 'mdc_adjfactor': 'trade_dt',
             'mdc_tdate': 'trade_dt', 'mdc_maxpx': 'trade_dt', 'mdc_minpx': 'trade_dt', 'mdc_stpt': 'trade_dt',
             'sec_status': 'trade_dt','sec_name': 'trade_dt','mdc_trade_status': 'trade_dt',
             'fmarketval': 'trade_dt', 'rdexpense': 'report_dt', 'float_a_shr_today': 'trade_dt',
             'stmnote_finexp': 'report_dt', 'roe': 'report_dt', 'operateincome': 'report_dt',
             'stmnote_finexp_fa': 'report_dt', 'stm_is': 'report_dt', 'ebit_fa': 'report_dt', 'ebitda_fa': 'report_dt',
             'fcff': 'report_dt', 'exinterestdebt_current': 'report_dt', 'exinterestdebt_noncurrent': 'report_dt',
             'investcapital': 'report_dt', 'ocftoprofit': 'report_dt', 'cashtoliqdebtwithinterest': 'report_dt',
             'profitnotice_date': 'report_dt', 'profitnotice_netprofitmin': 'report_dt',
             'profitnotice_netprofitmax': 'report_dt', 'profitnotice_changemin': 'report_dt',
             'profitnotice_changemax': 'report_dt', 'ann_dt_kb': 'report_dt', 'yoysales_kb': 'report_dt',
             'yoyop_kb': 'report_dt', 'yoyebt_kb': 'report_dt', 'yoynetprofit_deducted_kb': 'report_dt',
             'yoyeps_basic_kb': 'report_dt', 'roe_yearly_kb': 'report_dt'},
    'gaya_pre': {'stpt': 'trade_dt'},
    'gaya_pre_2': { 'mdc_pre_close': 'trade_dt', 'mdc_adjfactor': 'trade_dt', 'mdc_tdate': 'trade_dt', 'mdc_trade_status': 'trade_dt'},
    'wind_vip_pre': {'adjfactor': 'trade_dt', 'pre_close': 'trade_dt', 'trade_status': 'trade_dt', 'maxup': 'trade_dt',
                     'maxdown': 'trade_dt'},
    'wind_vip': {'eps_basic': 'report_dt', 'roe_basic': 'report_dt', 'roa2': 'report_dt', 'roa': 'report_dt',
                 'roic': 'report_dt', 'grossprofitmargin': 'report_dt', 'optoebt': 'report_dt',
                 'profittogr': 'report_dt', 'optogr': 'report_dt', 'operateexpensetogr': 'report_dt',
                 'operateincometoebt': 'report_dt', 'investincometoebt': 'report_dt',
                 'nonoperateprofittoebt': 'report_dt', 'ocftosales': 'report_dt', 'debttoassets': 'report_dt',
                 'assetstoequity': 'report_dt', 'catoassets': 'report_dt', 'intdebttototalcap': 'report_dt',
                 'currentdebttodebt': 'report_dt', 'current': 'report_dt', 'quick': 'report_dt',
                 'ocftodebt': 'report_dt', 'invturn': 'report_dt', 'arturn': 'report_dt',
                 'caturn': 'report_dt', 'faturn': 'report_dt', 'assetsturn1': 'report_dt',
                 'roe_ttm2': 'report_dt', 'roa2_ttm2': 'report_dt', 'netprofittoassets': 'report_dt',
                 'roic_ttm2': 'report_dt', 'netprofitmargin_ttm2': 'report_dt',
                 'grossprofitmargin_ttm2': 'report_dt', 'profittogr_ttm2': 'report_dt',
                 'optogr_ttm2': 'report_dt', 'gctogr_ttm2': 'report_dt', 'netprofittoor_ttm': 'report_dt',
                 'operateincometoebt_ttm2': 'report_dt', 'ebttoor_ttm': 'report_dt',
                 'ocftoor_ttm2': 'report_dt', 'gr_ttm2': 'report_dt', 'gc_ttm2': 'report_dt',
                 'grossmargin_ttm2': 'report_dt', 'interestexpense_ttm': 'report_dt',
                 'profit_ttm2': 'report_dt', 'operatecashflow_ttm2': 'report_dt',
                 'cashflow_ttm2': 'report_dt', 'fcff': 'report_dt', 'fcfe': 'report_dt',
                 'qfa_operateincome': 'report_dt', 'qfa_roe': 'report_dt', 'qfa_roa': 'report_dt',
                 'qfa_netprofitmargin': 'report_dt', 'qfa_grossprofitmargin': 'report_dt',
                 'qfa_profittogr': 'report_dt', 'qfa_operateincometoebt': 'report_dt',
                 'qfa_ocftosales': 'report_dt', 'qfa_ocftoor': 'report_dt', 'qfa_yoygr': 'report_dt',
                 'qfa_yoysales': 'report_dt', 'qfa_yoyop': 'report_dt', 'qfa_yoyprofit': 'report_dt',
                 'yoy_equity': 'report_dt', 'yoy_tr': 'report_dt', 'yoycf': 'report_dt',
                 'yoyeps_basic': 'report_dt', 'yoynetprofit': 'report_dt', 'yoyocf': 'report_dt',
                 'yoyocfps': 'report_dt', 'yoyop': 'report_dt', 'yoyroe': 'report_dt',
                 'stm_issuingdate': 'report_dt', 'yoyprofit': 'report_dt', 'ebitdatosales': 'report_dt',
                 'ocftocf': 'report_dt', 'fcftocf': 'report_dt', 'ocftoop': 'report_dt',
                 'ocftoassets': 'report_dt', 'longdebttolongcaptial': 'report_dt',
                 'longcapitaltoinvestment': 'report_dt', 'currentdebttoequity': 'report_dt',
                 'ncatoequity': 'report_dt', 'longdebttodebt': 'report_dt', 'operatecaptialturn': 'report_dt',
                 'apturn': 'report_dt', 'ebittoassets2': 'report_dt', 'qfa_yoyeps': 'report_dt',
                 'yoy_assets': 'report_dt', 'yoy_cash': 'report_dt', 'yoy_fixedassets': 'report_dt',
                 'yoydebt': 'report_dt', 'ocftodividend': 'report_dt', 'ocftointerest': 'report_dt',
                 'stmnote_salestop5_pct': 'report_dt', 'tot_assets': 'report_dt', 'tot_liab': 'report_dt',
                 'tot_non_cur_liab': 'report_dt', 'tot_equity': 'report_dt', 'cashtostdebt': 'report_dt',
                 'qfa_grossmargin': 'report_dt', 'acctandnotes_payable': 'report_dt',
                 'acctandnotes_rcv': 'report_dt', 'fa_retainedearn_ttm': 'trade_dt', 'fa_roc_ttm': 'trade_dt',
                 'fa_protocost_ttm': 'trade_dt', 'fa_ebittogr_ttm': 'trade_dt', 'fa_taxratio_ttm': 'trade_dt',
                 'fa_acca_ttm': 'trade_dt', 'fa_berryratio_ttm': 'trade_dt',
                 'fa_cashrecovratio_ttm': 'trade_dt', 'fa_ltdebttoasset': 'trade_dt',
                 'fa_equitytofixedasset': 'trade_dt', 'fa_intangassetratio': 'trade_dt',
                 'fa_debttotangibleafybl': 'trade_dt', 'fa_ocftointerestdebt_ttm': 'trade_dt',
                 'fa_ocftonetdebt_ttm': 'trade_dt', 'fa_cfotocurliabs_ttm': 'trade_dt',
                 'fa_faturn_ttm': 'trade_dt', 'fa_invturn_ttm': 'trade_dt',
                 'fa_currtassetstrate_ttm': 'trade_dt', 'fa_naturn_ttm': 'trade_dt',
                 'fa_ncgr_ttm': 'trade_dt', 'fa_tpgr_ttm': 'trade_dt', 'fa_oigr_ttm': 'trade_dt',
                 'fa_nppcgr_ttm': 'trade_dt', 'fa_cfogr_ttm': 'trade_dt', 'fa_cffgr_ttm': 'trade_dt',
                 'fa_cfigr_ttm': 'trade_dt', 'fa_gpmgr_ttm': 'trade_dt', 'pcf_ncf_ttm': 'trade_dt',
                 'val_ortoev_ttm': 'trade_dt', 'val_tatoev': 'trade_dt', 'val_mvtofcff': 'trade_dt',
                 'dividendyield2': 'trade_dt', 'pe_ttm': 'trade_dt', 'pb_lf': 'trade_dt',
                 'pcf_ocf_ttm': 'trade_dt', 'ps_ttm': 'trade_dt', 'share_pledgeda_pct_holder': 'trade_dt',
                 'close': 'trade_dt', 'adjfactor': 'trade_dt', 'pre_close': 'trade_dt', 'premiumrate_ah': 'trade_dt',
                 'codechangedate': 'trade_dt', 'trade_code': 'trade_dt', 'precode': 'trade_dt', 'concept': 'trade_dt',
                 'free_float_shares': 'trade_dt', 'total_shares': 'trade_dt', 'float_a_shares': 'trade_dt',
                 'turn': 'trade_dt', 'free_turn': 'trade_dt', 'susp_reason': 'trade_dt'},
    'wind_vip_us': {'close': 'trade_dt', 'adjfactor': 'trade_dt', 'industry': 'trade_dt', 'high': 'trade_dt',
                    'open': 'trade_dt', 'low': 'trade_dt'},
                    }

table_name_dict = {'con_forecast_c2_stk': 'trade_dt', 'news_csinextdayweight': 'trade_dt',
                   'ashareeodprices': 'trade_dt', 'factor_d_marketindex': 'trade_dt',
                   'inx_closeweight': 'trade_dt', 'ashareeodprices-duplicate':'trade_dt'}
