include("@CMAKE_INSTALL_PREFIX@/@INSTALL_CONFIGDIR@/@PROJECT_EXPORT_NAME@.cmake")
set(@PROJECT_NAME@_INCLUDE_DIR @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@)
set(@PROJECT_NAME@_LIB_DIR @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@)
set(@PROJECT_NAME@_CONFIG_DIR @CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@/cmake/@PROJECT_NAME@)

find_package(Arrow REQUIRED)
find_package(Parquet REQUIRED)

add_compile_definitions(
  ATSFACTOR_DEVELOPMENT_MODE=0
  ATSFACTOR_USE_TASKFLOW=@ATSFACTOR_USE_TASKFLOW@
  ATSFACTOR_USE_OPENMP=@ATSFACTOR_USE_OPENMP@
)