# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RpcService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RpcService.proto',
  package='quantfactor',
  syntax='proto3',
  serialized_pb=_b('\n\x10RpcService.proto\x12\x0bquantfactor\"#\n\x0cPrintRequest\x12\x13\n\x0bpickledArgs\x18\x01 \x01(\x0c\"\x07\n\x05\x45mpty2M\n\x0bQuantFactor\x12>\n\x0bremotePrint\x12\x19.quantfactor.PrintRequest\x1a\x12.quantfactor.Empty\"\x00\x62\x06proto3')
)




_PRINTREQUEST = _descriptor.Descriptor(
  name='PrintRequest',
  full_name='quantfactor.PrintRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pickledArgs', full_name='quantfactor.PrintRequest.pickledArgs', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=68,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='quantfactor.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['PrintRequest'] = _PRINTREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrintRequest = _reflection.GeneratedProtocolMessageType('PrintRequest', (_message.Message,), dict(
  DESCRIPTOR = _PRINTREQUEST,
  __module__ = 'RpcService_pb2'
  # @@protoc_insertion_point(class_scope:quantfactor.PrintRequest)
  ))
_sym_db.RegisterMessage(PrintRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'RpcService_pb2'
  # @@protoc_insertion_point(class_scope:quantfactor.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_QUANTFACTOR = _descriptor.ServiceDescriptor(
  name='QuantFactor',
  full_name='quantfactor.QuantFactor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=79,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='remotePrint',
    full_name='quantfactor.QuantFactor.remotePrint',
    index=0,
    containing_service=None,
    input_type=_PRINTREQUEST,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUANTFACTOR)

DESCRIPTOR.services_by_name['QuantFactor'] = _QUANTFACTOR

# @@protoc_insertion_point(module_scope)
