# _*_ coding:utf-8 _*_

tables = ["wind.AShareBalanceSheet","wind.AShareCashFlow","wind.AShareIncome","wind.AShareProfitExpress",
          "wind.AShareProfitNotice","wind.AShareFinancialIndicator","wind.AShareTTMHis",
          "wind.AShareANNFinancialIndicator","wind.AShareIssuingDatePredict","wind.AShareDescription",
          "wind.AShareIndustriesClassCITICS","wind.AShareST","wind.AShareDividend",
          "wind.AShareMonthlyReportsofBrokers","wind.AShareEODDerivativeIndicator","wind.AShareEODPrices",
          "wind.AIndexEODPrices","wind.AShareManagementHoldReward","wind.AShareMoneyFlow",
          "wind.SHSCDailyStatistics","wind.SHSCShortselling","wind.SHSCTop10ActiveStocks",
          "wind.SHSCChannelholdings","wind.ASharePledgeproportion","wind.AShareFreeFloatCalendar",
          "wind.ChinaMutualFundAssetPortfolio","wind.CMFOtherPortfolio","wind.ChinaMutualFundIndPortfolio",
          "wind.ChinaMutualFundStockPortfolio","wind.ChinaMutualFundBondPortfolio",
          "wind.AShareMarginSubject","wind.AShareBlockTrade","wind.AShareStrangeTradedetail",
          "wind.AShareStrangeTrade","wind.AShareHolderNumber","wind.AShareFloatHolder",
          "wind.AShareInsiderTrade","wind.AShareMajorHolderPlanHold","wind.AShareinstHolderDerData",
          "wind.AShareL2Indicators","wind.CMMFPortfolioPTM","wind.AShareIndustriesCode",
          "wind.AShareCapitalization","wind.AShareFreeFloat","wind.AShareIPO","wind.AShareAgency",
          "wind.AShareCOCapitaloperation","wind.AshareStockRepo","wind.AShareCorporateFinance",
          "wind.AShareIssueCommAudit","wind.AShareEquityDivision","wind.AShareStaff","wind.IPOCompRFA",
          "wind.IECMemberList","wind.AShareLeadUnderwriter","wind.AShareRightIssue","wind.AShareSEO",
          "wind.AShareEXRightDividendRecord","wind.AShareCompRestricted","wind.ASharePlacementDetails",
          "wind.ASharePlacementInfo","wind.IPOInquiryDetails","wind.AShareManagement",
          "wind.AShareIncDescription","wind.AShareIncQuantityPrice","wind.AShareIncQuantityDetails",
          "wind.AShareIncExercisePct","wind.AShareIncExecQtyPri","wind.AShareEsopDescription",
          "wind.AShareEsopTradingInfo","wind.AShareStaffStructure","wind.AShareEquityPledgeInfo",
          "wind.AShareInsideHolder","wind.htzqedbdzzbs","wind.AIndexIndustriesEODCITICS",
          "wind.SIndexPerformance","wind.BOIndexWeightsWIND","wind.AShareStyleCoefficient",
          "wind.AShareMjrHolderTrade","wind.AShareTypeCode","wind.AShareTradingSuspension",
          "wind.AShareMainandnoteitems","wind.AShareTechIndicators","wind.AshareintensitytrendADJ",
          "wind.AShareEnergyindexADJ","wind.AShareswingReversetrendADJ","wind.AIndexFinancialderivative",
          "wind.FinNotesDetail","wind.AShareIBrokerIndicator","wind.AShareInsuranceIndicator",
          "wind.AShareBankIndicator","wind.AShareSalesSegment","wind.Top5ByLongTermBorrowing",
          "wind.Top5ByOperatingIncome","wind.AshareOtherreceivables","wind.AShareFinancialExpense",
          "wind.AshareInventorydetails","wind.AshareFinancialaccounts","wind.Top5ByAccountsReceivable",
          "wind.AShareMarginTrade","wind.AShareMarginTradeSum","gogoal.con_forecast_stk",
          "gogoal.con_forecast_schedule","gogoal_new.stock_order3","gogoal_new.stock_report_adjustment",
          "gogoal_new.stock_report_number","gogoal_new.stock_order2","gogoal_new.stock_report_adjustment2",
          "gogoal_new.stock_concern_level","gogoal_new.con_stock_deviation3","gogoal_new.con_stock_deviation2",
          "gogoal_new.con_stock_deviation","gogoal_new.stock_diversity","gogoal_new.stock_emotion",
          "gogoal_new.stock_report_extremum","gogoal.der_report_subtable","gogoal.cmb_report_score_adjust",
          "gogoal.i_organ_score","gogoal.report_author","gogoal.cmb_report_adjust","gogoal.gg_org_list",
          "gogoal.i_report_type","gogoal_new.author_core_type","gogoal_new.author_core",
          "gogoal.cmb_report_subtable","gogoal_new.author_pj","gogoal_new.author_pjhb",
          "gogoal_new.t_great_author","gogoal.con_forecast_c2_stk","gogoal.con_forecast_c3_cgb_stk",
          "gogoal.con_forecast_c3_stk","gogoal.con_forecast_cb_stk","gogoal.researcher_info",
          "gogoal_new.t_author_honor","gogoal.der_report_research","gogoal.cmb_report_research"]

hours = ['01','02','03','04','05','06','07','08','09','10','11','12',
         '13','14','15','16','17','18','19','20','21','22','23','00']

