# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

# 注意，protoc编译生成后没有这个Rpc前缀，最好手动加上
import Utils.Rpc.RpcService_pb2 as RpcService__pb2


class QuantFactorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.remotePrint = channel.unary_unary(
        '/quantfactor.QuantFactor/remotePrint',
        request_serializer=RpcService__pb2.PrintRequest.SerializeToString,
        response_deserializer=RpcService__pb2.Empty.FromString,
        )


class QuantFactorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def remotePrint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QuantFactorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'remotePrint': grpc.unary_unary_rpc_method_handler(
          servicer.remotePrint,
          request_deserializer=RpcService__pb2.PrintRequest.FromString,
          response_serializer=RpcService__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'quantfactor.QuantFactor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
