# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import IMDPeriodDataService_pb2 as IMDPeriodDataService__pb2


class IMDPeriodDataServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getMDPeriodData = channel.unary_stream(
        '/com.htsc.mdc.hawkeye.model.gservice.IMDPeriodDataService/getMDPeriodData',
        request_serializer=IMDPeriodDataService__pb2.MDPeriodDataRpcRequest.SerializeToString,
        response_deserializer=IMDPeriodDataService__pb2.MDPeriodDataRpcResponse.FromString,
        )
    self.getMDPeriodDataByTimeOrder = channel.unary_stream(
        '/com.htsc.mdc.hawkeye.model.gservice.IMDPeriodDataService/getMDPeriodDataByTimeOrder',
        request_serializer=IMDPeriodDataService__pb2.MDPeriodDataTimeOrderRpcRequest.SerializeToString,
        response_deserializer=IMDPeriodDataService__pb2.MDPeriodDataRpcResponse.FromString,
        )


class IMDPeriodDataServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getMDPeriodData(self, request, context):
    """query PeriodData(TWAP,VWAP)
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMDPeriodDataByTimeOrder(self, request, context):
    """query PeriodData(TWAP,VWAP) by MDTime Order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IMDPeriodDataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getMDPeriodData': grpc.unary_stream_rpc_method_handler(
          servicer.getMDPeriodData,
          request_deserializer=IMDPeriodDataService__pb2.MDPeriodDataRpcRequest.FromString,
          response_serializer=IMDPeriodDataService__pb2.MDPeriodDataRpcResponse.SerializeToString,
      ),
      'getMDPeriodDataByTimeOrder': grpc.unary_stream_rpc_method_handler(
          servicer.getMDPeriodDataByTimeOrder,
          request_deserializer=IMDPeriodDataService__pb2.MDPeriodDataTimeOrderRpcRequest.FromString,
          response_serializer=IMDPeriodDataService__pb2.MDPeriodDataRpcResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.htsc.mdc.hawkeye.model.gservice.IMDPeriodDataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))