# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MDKLine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import EMDKLineType_pb2 as EMDKLineType__pb2
import EMDPeriodType_pb2 as EMDPeriodType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MDKLine.proto',
  package='com.htsc.mdc.model',
  syntax='proto3',
  serialized_pb=_b('\n\rMDKLine.proto\x12\x12\x63om.htsc.mdc.model\x1a\x12\x45MDKLineType.proto\x1a\x13\x45MDPeriodType.proto\"\xd6\x04\n\x07MDKLine\x12\x12\n\nMDRecordID\x18\x01 \x01(\t\x12\x33\n\tKLineType\x18\x02 \x01(\x0e\x32 .com.htsc.mdc.model.EMDKLineType\x12\x12\n\nSecurityID\x18\x03 \x01(\t\x12\x16\n\x0eHTSCSecurityID\x18\x04 \x01(\t\x12\x0e\n\x06MDDate\x18\x05 \x01(\t\x12\x0e\n\x06MDTime\x18\x06 \x01(\t\x12\x0e\n\x06OpenPx\x18\x07 \x01(\x01\x12\x0f\n\x07\x43losePx\x18\x08 \x01(\x01\x12\x0e\n\x06HighPx\x18\t \x01(\x01\x12\r\n\x05LowPx\x18\n \x01(\x01\x12\x11\n\tNumTrades\x18\x0b \x01(\x03\x12\x18\n\x10TotalVolumeTrade\x18\x0c \x01(\x01\x12\x17\n\x0fTotalValueTrade\x18\r \x01(\x01\x12\x35\n\nPeriodType\x18\x0e \x01(\x0e\x32!.com.htsc.mdc.model.EMDPeriodType\x12\x0c\n\x04IOPV\x18\x0f \x01(\x01\x12\x14\n\x0cOpenInterest\x18\x10 \x01(\x01\x12\x13\n\x0bSettlePrice\x18\x11 \x01(\x01\x12\x14\n\x0c\x45xchangeDate\x18\x12 \x01(\t\x12\x14\n\x0c\x45xchangeTime\x18\x13 \x01(\t\x12\x14\n\x0c\x44\x61teOfOpenPx\x18\x14 \x01(\t\x12\x15\n\rDateOfClosePx\x18\x15 \x01(\t\x12\x14\n\x0c\x44\x61teOfHighPx\x18\x16 \x01(\t\x12\x13\n\x0b\x44\x61teOfLowPx\x18\x17 \x01(\t\x12\x12\n\nRealHighPx\x18\x18 \x01(\x01\x12\x11\n\tRealLowPx\x18\x19 \x01(\x01\x12\x15\n\rKLineCategory\x18\x1a \x01(\x05\x42(\n\x12\x63om.htsc.mdc.modelB\rMDKLineProtosH\x01\xa0\x01\x01\x62\x06proto3')
  ,
  dependencies=[EMDKLineType__pb2.DESCRIPTOR,EMDPeriodType__pb2.DESCRIPTOR,])




_MDKLINE = _descriptor.Descriptor(
  name='MDKLine',
  full_name='com.htsc.mdc.model.MDKLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MDRecordID', full_name='com.htsc.mdc.model.MDKLine.MDRecordID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='KLineType', full_name='com.htsc.mdc.model.MDKLine.KLineType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SecurityID', full_name='com.htsc.mdc.model.MDKLine.SecurityID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HTSCSecurityID', full_name='com.htsc.mdc.model.MDKLine.HTSCSecurityID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDDate', full_name='com.htsc.mdc.model.MDKLine.MDDate', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MDTime', full_name='com.htsc.mdc.model.MDKLine.MDTime', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OpenPx', full_name='com.htsc.mdc.model.MDKLine.OpenPx', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ClosePx', full_name='com.htsc.mdc.model.MDKLine.ClosePx', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HighPx', full_name='com.htsc.mdc.model.MDKLine.HighPx', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LowPx', full_name='com.htsc.mdc.model.MDKLine.LowPx', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NumTrades', full_name='com.htsc.mdc.model.MDKLine.NumTrades', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TotalVolumeTrade', full_name='com.htsc.mdc.model.MDKLine.TotalVolumeTrade', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TotalValueTrade', full_name='com.htsc.mdc.model.MDKLine.TotalValueTrade', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PeriodType', full_name='com.htsc.mdc.model.MDKLine.PeriodType', index=13,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IOPV', full_name='com.htsc.mdc.model.MDKLine.IOPV', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='OpenInterest', full_name='com.htsc.mdc.model.MDKLine.OpenInterest', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SettlePrice', full_name='com.htsc.mdc.model.MDKLine.SettlePrice', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ExchangeDate', full_name='com.htsc.mdc.model.MDKLine.ExchangeDate', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ExchangeTime', full_name='com.htsc.mdc.model.MDKLine.ExchangeTime', index=18,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DateOfOpenPx', full_name='com.htsc.mdc.model.MDKLine.DateOfOpenPx', index=19,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DateOfClosePx', full_name='com.htsc.mdc.model.MDKLine.DateOfClosePx', index=20,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DateOfHighPx', full_name='com.htsc.mdc.model.MDKLine.DateOfHighPx', index=21,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DateOfLowPx', full_name='com.htsc.mdc.model.MDKLine.DateOfLowPx', index=22,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RealHighPx', full_name='com.htsc.mdc.model.MDKLine.RealHighPx', index=23,
      number=24, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RealLowPx', full_name='com.htsc.mdc.model.MDKLine.RealLowPx', index=24,
      number=25, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='KLineCategory', full_name='com.htsc.mdc.model.MDKLine.KLineCategory', index=25,
      number=26, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=677,
)

_MDKLINE.fields_by_name['KLineType'].enum_type = EMDKLineType__pb2._EMDKLINETYPE
_MDKLINE.fields_by_name['PeriodType'].enum_type = EMDPeriodType__pb2._EMDPERIODTYPE
DESCRIPTOR.message_types_by_name['MDKLine'] = _MDKLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MDKLine = _reflection.GeneratedProtocolMessageType('MDKLine', (_message.Message,), dict(
  DESCRIPTOR = _MDKLINE,
  __module__ = 'MDKLine_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.mdc.model.MDKLine)
  ))
_sym_db.RegisterMessage(MDKLine)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\022com.htsc.mdc.modelB\rMDKLineProtosH\001\240\001\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)