# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indexTrading.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='indexTrading.proto',
  package='com.htsc.xquant.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x12indexTrading.proto\x12\x18\x63om.htsc.xquant.protobuf\"Q\n\x16GetIndexTradingRequest\x12\x12\n\nplate_type\x18\x01 \x01(\x05\x12\x11\n\tdate_time\x18\x02 \x01(\t\x12\x10\n\x08plate_iD\x18\x03 \x01(\t\"\x86\x01\n\x17GetIndexTradingResponse\x12\x12\n\nresultCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x46\n\x10indexTradingList\x18\x03 \x03(\x0b\x32,.com.htsc.xquant.protobuf.IndexTradingDetail\"\xab\x01\n\x12IndexTradingDetail\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tplateType\x18\x02 \x01(\x03\x12\x16\n\x0einxTradingCode\x18\x03 \x01(\t\x12\x13\n\x0binxSecuAbbr\x18\x04 \x01(\t\x12\x13\n\x0btradingCode\x18\x05 \x01(\x03\x12\x10\n\x08secuAbbr\x18\x06 \x01(\t\x12\x12\n\ntradingDay\x18\x07 \x01(\t\x12\x0e\n\x06weight\x18\x08 \x01(\x03\x32\x8f\x01\n\x13IndexTradingService\x12x\n\x0fgetIndexTrading\x12\x30.com.htsc.xquant.protobuf.GetIndexTradingRequest\x1a\x31.com.htsc.xquant.protobuf.GetIndexTradingResponse\"\x00\x42\x39\n\'com.htsc.xquant.engine.protobuf.tradingB\x0cIndexTradingP\x01\x62\x06proto3')
)




_GETINDEXTRADINGREQUEST = _descriptor.Descriptor(
  name='GetIndexTradingRequest',
  full_name='com.htsc.xquant.protobuf.GetIndexTradingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plate_type', full_name='com.htsc.xquant.protobuf.GetIndexTradingRequest.plate_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_time', full_name='com.htsc.xquant.protobuf.GetIndexTradingRequest.date_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plate_iD', full_name='com.htsc.xquant.protobuf.GetIndexTradingRequest.plate_iD', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=129,
)


_GETINDEXTRADINGRESPONSE = _descriptor.Descriptor(
  name='GetIndexTradingResponse',
  full_name='com.htsc.xquant.protobuf.GetIndexTradingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resultCode', full_name='com.htsc.xquant.protobuf.GetIndexTradingResponse.resultCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.htsc.xquant.protobuf.GetIndexTradingResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indexTradingList', full_name='com.htsc.xquant.protobuf.GetIndexTradingResponse.indexTradingList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=266,
)


_INDEXTRADINGDETAIL = _descriptor.Descriptor(
  name='IndexTradingDetail',
  full_name='com.htsc.xquant.protobuf.IndexTradingDetail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.htsc.xquant.protobuf.IndexTradingDetail.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plateType', full_name='com.htsc.xquant.protobuf.IndexTradingDetail.plateType', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inxTradingCode', full_name='com.htsc.xquant.protobuf.IndexTradingDetail.inxTradingCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inxSecuAbbr', full_name='com.htsc.xquant.protobuf.IndexTradingDetail.inxSecuAbbr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tradingCode', full_name='com.htsc.xquant.protobuf.IndexTradingDetail.tradingCode', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secuAbbr', full_name='com.htsc.xquant.protobuf.IndexTradingDetail.secuAbbr', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tradingDay', full_name='com.htsc.xquant.protobuf.IndexTradingDetail.tradingDay', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='com.htsc.xquant.protobuf.IndexTradingDetail.weight', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=440,
)

_GETINDEXTRADINGRESPONSE.fields_by_name['indexTradingList'].message_type = _INDEXTRADINGDETAIL
DESCRIPTOR.message_types_by_name['GetIndexTradingRequest'] = _GETINDEXTRADINGREQUEST
DESCRIPTOR.message_types_by_name['GetIndexTradingResponse'] = _GETINDEXTRADINGRESPONSE
DESCRIPTOR.message_types_by_name['IndexTradingDetail'] = _INDEXTRADINGDETAIL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetIndexTradingRequest = _reflection.GeneratedProtocolMessageType('GetIndexTradingRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETINDEXTRADINGREQUEST,
  __module__ = 'indexTrading_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.GetIndexTradingRequest)
  ))
_sym_db.RegisterMessage(GetIndexTradingRequest)

GetIndexTradingResponse = _reflection.GeneratedProtocolMessageType('GetIndexTradingResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETINDEXTRADINGRESPONSE,
  __module__ = 'indexTrading_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.GetIndexTradingResponse)
  ))
_sym_db.RegisterMessage(GetIndexTradingResponse)

IndexTradingDetail = _reflection.GeneratedProtocolMessageType('IndexTradingDetail', (_message.Message,), dict(
  DESCRIPTOR = _INDEXTRADINGDETAIL,
  __module__ = 'indexTrading_pb2'
  # @@protoc_insertion_point(class_scope:com.htsc.xquant.protobuf.IndexTradingDetail)
  ))
_sym_db.RegisterMessage(IndexTradingDetail)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\'com.htsc.xquant.engine.protobuf.tradingB\014IndexTradingP\001'))

_INDEXTRADINGSERVICE = _descriptor.ServiceDescriptor(
  name='IndexTradingService',
  full_name='com.htsc.xquant.protobuf.IndexTradingService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=443,
  serialized_end=586,
  methods=[
  _descriptor.MethodDescriptor(
    name='getIndexTrading',
    full_name='com.htsc.xquant.protobuf.IndexTradingService.getIndexTrading',
    index=0,
    containing_service=None,
    input_type=_GETINDEXTRADINGREQUEST,
    output_type=_GETINDEXTRADINGRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_INDEXTRADINGSERVICE)

DESCRIPTOR.services_by_name['IndexTradingService'] = _INDEXTRADINGSERVICE

# @@protoc_insertion_point(module_scope)
